### ISSUE TITLE
VR Interactions

### ISSUE THREAD

**Issue by DaXcess** [DaXcess/LCVR#10]
This is an initial draft for implementing VR interactions within the mod. VR Interactions will not be added in the first release of the mod, but will be added at a later date.

- [x] Third person hand movement
- [x] Correctly holding large items
- [x] Swinging the shovel/signs using motion instead of buttons
- [x] ~~Throwing items (this would be so cool)~~ Incompatible with vanilla clients
- [x] Spray paint? I'm not sure if this could be implemented easily inside the #9, in which case this point isn't needed

*As always, list is subject to change*

**Comment by patrlim** [comment]
third person IK would be amazing to have if you add motion controls.

**Comment by DaXcess** [comment]
> third person IK would be amazing to have if you add motion controls.

Motion controls are already in, so I may add third person IK before the initial release

**Comment by ggezgaming** [comment]
Don't know whether this comment counts under this or Vr controls, but how would other clients handle the irregular playermodel motion from a vr player? Would the mod have a VR and non-VR version, that way people without VR can still play with people with VR and see the goofy shit they're doing?

**Comment by DaXcess** [comment]
> Don't know whether this comment counts under this or Vr controls, but how would other clients handle the irregular playermodel motion from a vr player? Would the mod have a VR and non-VR version, that way people without VR can still play with people with VR and see the goofy shit they're doing?

Other clients will require the mod too, and also for clients to see each other's movement the server host must have the mod as well, since it requires extra network rpc's. I think I will stick to a single mod for both VR and non-VR and make it configurable. The mod already correctly disables VR if it is not able to start VR (i.e. no headset connected, or not owning a headset at all). It also already can disable VR even if a headset is connected by passing "--disable-vr" to the game.
