### ISSUE TITLE
Switching between Item Slots using HotbarPlus moves over two slots instead of one

### ISSUE THREAD

**Issue by Meeecoh** [DaXcess/LCVR#101]
I'm using HotbarPlus v1.5.2 by FlipMods alongside LCVR to have 6 item slots instead of the normal 4. 
Tapping the right joystick Y in either direction causes the active item slot to be moved two spaces over instead of one.
I'm not sure if this is a HotbarPlus problem or a LCVR problem, but I'm just putting this out there.

**Comment by bavninja** [comment]
Look inside settings you can fix it, think its something like fast swapping

**Comment by bavninja** [comment]
Inside hotbarplus this is also a thing with flatscreen if your scrollwheel is to sensitive
