### ISSUE TITLE
UnityOpenXR Unknown Assembly

### ISSUE THREAD

**Issue by gulopbr** [DaXcess/LCVR#11]
I've successfully made a build following instructions from COMPILING.md. Visual Studio compiled with no errors, however when I try to open the game the BeepInEX console outputs the following error:

```
[Info   :      LCVR] Plugin LCVR is starting...
[Warning: Unity Log] The referenced script (LmaoScript) on this Behaviour is missing!
[Warning: Unity Log] The referenced script on this Behaviour (Game Object 'ALiteralCube') is missing!
[Warning: Unity Log] The referenced script (AnimateHandOnInput) on this Behaviour is missing!
[Warning: Unity Log] The referenced script on this Behaviour (Game Object '') is missing!
[Warning: Unity Log] The referenced script (AnimateHandOnInput) on this Behaviour is missing!
[Warning: Unity Log] The referenced script on this Behaviour (Game Object '') is missing!
[Info   :      LCVR] Loading VR...
[Info   : Unity Log] XRGeneral Settings awakening...
[Error  : Unity Log] DllNotFoundException: UnityOpenXR assembly:<unknown assembly> type:<unknown type> member:(null)
Stack trace:
UnityEngine.XR.OpenXR.OpenXRLoaderBase.Initialize () (at <6d442ad8e5f741e3bf162b65a9e5972b>:0)
UnityEngine.XR.Management.XRManagerSettings.InitializeLoaderSync () (at <b6cb980159cd47e39b81ef7848f9423a>:0)
UnityEngine.XR.Management.XRGeneralSettings.InitXRSDK () (at <b6cb980159cd47e39b81ef7848f9423a>:0)
System.Reflection.RuntimeMethodInfo.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at <787acc3c9a4c471ba7d971300105af24>:0)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.RuntimeMethodInfo.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at <787acc3c9a4c471ba7d971300105af24>:0)
System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) (at <787acc3c9a4c471ba7d971300105af24>:0)
LethalCompanyVR.Plugin.InitializeXRRuntime () (at C:/Users/Gustavo/Desktop/LCVR/Plugin.cs:138)
LethalCompanyVR.Plugin.InitVRLoader () (at C:/Users/Gustavo/Desktop/LCVR/Plugin.cs:66)
LethalCompanyVR.Plugin.Awake () (at C:/Users/Gustavo/Desktop/LCVR/Plugin.cs:60)
UnityEngine.GameObject:AddComponent(Type)
BepInEx.Bootstrap.Chainloader:Start()
UnityEngine.Rendering.HighDefinition.HDRenderPipelineAsset:OnEnable()
```

While the error mentions of a DLL not found, all the necessary dlls are in the folder of the plugin, including Unity.XR.OpenXR.dll. Does the plugin folder needs a specific structure?

My guess is that Harmony is not being able to patch the game for some reason, but I'm not sure if it's a problem with my build or I'm missing something else. 

I also tested with Virtual Desktop, SteamLink and AirLink and all OpenXR runtimes I have available, being SteamVR, Oculus and VDXR, the error didn't change. 

I also believe I have all necessary dependencies, my game version is 45, BeepinEX 5.4.2 for Mono, and the .NET desktop target in Visual Studio and .NET SDK 8.0 since it was specified in the docs.

I apologize if it's a rookie mistake, I'm starting out with Unity modding development and I'm interested what could be the cause of this error. 

Thank you for your time,

Have a nice day

**Comment by DaXcess** [comment]
Hey there, the COMPILING.md documentation does not include the portion of how to install the game. That will eventually be a part of the main README.md (and upon release on thunderstore it will all be packaged in a correct format).

Since you have mentioned that you copied all the managed modules to the game folder, that does not seem to be the issue. My best guess would be that the **un**managed modules are not present (hinted at by the fact that it is trying to load `UnityOpenXR.dll` in your error logs). These dlls (found inside the `Libs/Plugins` folder) must also be copied to the game file before it would work, and IIRC that also counts for the UnitySubsystems folder, which should be copied to `Lethal Company_data`.
