### ISSUE TITLE
Shovel Misfire

### ISSUE THREAD

**Issue by keanine** [DaXcess/LCVR#114]
When holding the shovel if I turn my head quickly 90 degrees to the left, I hear the sound of the shovel being raised, and when I turn my head back to the right I hear the shovel swinging.

I haven't tested this on players/monsters yet to see if it actually does damage, but I'm guessing it's activating the shovels attack despite the fact I'm not lifting the controller above my head at all.

**Comment by DaXcess** [comment]
Shovel code has been changed a bit in the past 7 months, so might be fixed at this point
