### ISSUE TITLE
Audio devices are not being set correctly

### ISSUE THREAD

**Issue by Zeican** [DaXcess/LCVR#117]
So through some quick testing, it appears that the mod auto defaults the audio output to your vr headset's speakers (in this case it's the quest 2 speakers. I haven't tested if it does the same on other vr heasets as I don't own any other vr.

**Comment by TechGigant** [comment]
I have the same issue, please fix this issue as fast as you can. Disabling the VR mod fixes it, but that isn't a good solution if you still want to see other people in VR.

**Comment by TechGigant** [comment]
@DaXcess Please fix this.

**Comment by DaXcess** [comment]
Audio devices are not being managed through the mod or the game, this is something you will have to fix in your headset or the software that communicates with your headset
