### ISSUE TITLE
Difficulties using walkie-talkies.

### ISSUE THREAD

**Issue by CAYOK** [DaXcess/LCVR#118]
I play on Rift CV1 with default bindings. Turning on the walkie-talkie is really inconsistent, it would take multiple button presses and/or certain button combinations to turn on the walkie, it would not turn on at all by only pressing the left grip button. Then using the walkie-talkie with trigger, it will always think I'm holding the talk button down once I press trigger, sort of like a toggle. But this occurs a problem where the game stops letting me switch items, pick up items, open doors, and more. The only way to stop this is to go to my keyboard and turn off the walkie-talkie and turn it back on again.

**Comment by DaXcess** [comment]
No longer an issue since v1.2.0 since that contains a bindings fix and walkies are now triggered based on position near face
