### ISSUE TITLE
[Quest 3] Weird visual offset on the main menu

### ISSUE THREAD

**Issue by ExaltedZoro** [DaXcess/LCVR#122]
As far as I can tell on the quest 3 steam link the main menu has the eyes the wrong way round (it's showing what should be on the left eye to the right eye and vice versa). It's not a problem anywhere else in the game but it makes it a little difficult to navigate the menu.

**Comment by MasterChef5311** [comment]
same issue but i cant press any of the buttons cause its so zoomed in

**Comment by bavninja** [comment]
Make sure there is no other mods installed, I've only seen this issue so far with people who have mods incompatible mods installed

**Comment by ExaltedZoro** [comment]
The only other mod I had installed was morecompany but I'll have a look at trying it without it

**Comment by Draftier** [comment]
Did you guys ever figure out how to fix the swapped eyes things? One of my friends is having this same issue.

**Comment by Altived** [comment]
use the override compatibility check in the lcvr config or just remove some mods

**Comment by Nathan22211** [comment]
same here with a quest 3 + virtual desktop. What's odd is that it's only in the online menu and not the LAN menu, in-game in LAN mode it's fine oddly enough as well the only mod that I have that affects rendering would be HDlethalCompany but even removing that didn't work, and the only mod that is marked as having issues, mimics, doesn't affect rendering

**Comment by ExaltedZoro** [comment]
> use the override compatibility check in the lcvr config or just remove some mods

Disabling the override compat check worked, thank you so much :)

**Comment by ssrjazz** [comment]
Noticed this starting to happen with a recent update to MoreCompany.  Disabling the override compatability check does seem to fix the issue for me w/o any ill effects.   Wonder why this suddenly cropped up?

**Comment by Altived** [comment]
yeah more company is recently bugged (another issue to the infinite list) idk why this happened but atleast there is a fix for now
