### ISSUE TITLE
Add option to move where the controller is pointing

### ISSUE THREAD

**Issue by Zakru** [DaXcess/LCVR#126]
Currently locomotion is based on the current orientation of the head. This is quite inconvenient in a game where you have to be watching your back often, and personal preference on this also varies. There should be an option to use the direction a controller is pointing in to determine where the player should move.

**Comment by Zakru** [comment]
> The game (not the mod) applies movement based on the player body rotation, so this feature cannot be added

Huh, does the game take the movement input directly from VR controllers? Is there no way to intercept and rotate it based on the controller orientation?

**Comment by DaXcess** [comment]
The game takes only a Vector2 input (XY), 2d movement. It rotates this into 3d based on **the player rotation** (and that is used within a bunch of other functions in the game to check for slope steepness and a whole lot more). It is extremely unrealistic to rewrite that entirely for VR controller orientation (plus I'm terrible at rotations)
