### ISSUE TITLE
Controllers do not appear when launching the game

### ISSUE THREAD

**Issue by Pyroglyph** [DaXcess/LCVR#129]
My Index controllers work fine in the Steam menu but not in this game, where they do not appear at all. This happens with just this mod alone (with BepInEx, of course), so it can't be any other mod casing issues.

All the LCVR console logs seem normal, and by that I mean none of them mention missing controllers or anything.

Let me know if I can provide any more information that may be useful.

**Comment by DaXcess** [comment]
Old <1.2.0 issue, closing due to most likely no longer relevant
