### ISSUE TITLE
Main Menu VR Screen does not get initialized properly if the Steam SDK crashes

### ISSUE THREAD

**Issue by cHi3eN** [DaXcess/LCVR#131]
I tried the vr once with a meta quest 3 and it worked fine but now everytime I try to go online I am stuck with a  logo of the company, the image is blocked like this. I tried re-installing the game and mods but nothing change, everything seems normal in LAN mod.
![mon vié](https://github.com/DaXcess/LCVR/assets/156860625/e10ea935-67d6-4368-8d65-e2f4c9492d58)

**Comment by cHi3eN** [comment]
here's the logs:

[Info   :      LCVR] Started XR Display subsystem, welcome to VR!
[Message:   BepInEx] Chainloader startup complete
[Info   : Unity Log] Reference frame of the curve not set and XROrigin is not found, using global up as default.
[Info   : Unity Log] Reference frame of the curve not set and XROrigin is not found, using global up as default.
[Warning: Unity Log] MaximizedWindow is not currently supported on Windows, setting to FullsceenWindow instead
[Info   : Unity Log] Saving changed settings
[Warning: Unity Log] MaximizedWindow is not currently supported on Windows, setting to FullsceenWindow instead
[Info   : Unity Log] subcribing to steam callbacks
[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
Netcode.Transports.Facepunch.FacepunchTransport.Awake () (at <4d8977a13dda46f8bd577daf0c430926>:0)

[Info   : Unity Log] Reference frame of the curve not set and XROrigin is not found, using global up as default.
[Info   : Unity Log] Reference frame of the curve not set and XROrigin is not found, using global up as default.
[Warning: Unity Log] MaximizedWindow is not currently supported on Windows, setting to FullsceenWindow instead
[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
Steamworks.SteamClient.get_Name () (at <19bd4cc6a4004258bf538b05ac1133d6>:0)
GameNetworkManager+<waitFrameBeforeFindingUsername>d__48.MoveNext () (at <af9b1eec498a45aebd42601d6ab85015>:0)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <e27997765c1848b09d8073e5d642717a>:0)

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
Steamworks.SteamClient.get_IsLoggedOn () (at <19bd4cc6a4004258bf538b05ac1133d6>:0)
(wrapper dynamic-method) MenuManager.DMD<MenuManager::Start>(MenuManager)

**Comment by cHi3eN** [comment]
Well I tried reloading my steam app, entirely and it "initialized Steam SDK" I guess, so for now it's working again.

**Comment by DaXcess** [comment]
Fixed in 5701efbfc9ebd3443408075c270c6f7c83c22b8d
