### ISSUE TITLE
"Failed to start in VR mode" Error code

### ISSUE THREAD

**Issue by trafficconex** [DaXcess/LCVR#133]
I tried to use the LCVR mod to launch Lethal Company in VR, but got the error code "Failed to start in VR mode! Only non VR features are available!". I believe I saw a fix for this somewhere, but cannot find it again :(. Any fixes for this?
![Screenshot 2024-01-16 205219](https://github.com/DaXcess/LCVR/assets/156877320/4e32b3a8-e2eb-43f1-aee5-8fd4f863972a)

**Comment by Jastro** [comment]
You need to start Steam VR. When you have steam VR launched, execute the modded version of lethal company
