### ISSUE TITLE
[Enhancement] [v1.2.0] Improved interactions

### ISSUE THREAD

**Issue by DaXcess** [DaXcess/LCVR#135]
- [x] Pulling the start ship lever (with network sync, must be made vanilla compatible as well)
- [x] Holding up a chargeable item to the charger should charge them
- [x] Being able to **SMASH** the teleporter buttons
- [x] Monitor buttons (Buttons are moved to an easier to reach position)
- [x] Pushing ship door buttons
- [x] The bell at the company building
- [x] Ship horn lever pull
- [x] Configuration options to disable each of these interactions individually (aka restore the <1.2.0 functionality)
- [x] **Make it so the left hand can also be used for most interactions**
- [x] Breaker box switch flipping, requires pointer finger
- [x] ~~Maybe interior valves as well? Would have to check how this interaction is going to work though.~~ Hell no that looks like a rotation hell.
- [x] Add left hand binding to other controller profiles (currently it only works on the default profile)
- [x] Holding certain items in front of your face should activate them

**Comment by DaXcess** [comment]
> What about the buttons of the change camera and off monitor? is really annoying using right now on VR. We can hit it?

Yeah, the list is just things I have thought of, but more stuff can be added.
In this specific case though, it needs to be checked if the buttons aren't too far away from the player, since you can't lean over objects in this mod (you'll get pushed pack).

**Comment by bavninja** [comment]
For monitor buttons maybe someone could rework the original position for it so its closer to the player? Like what is currently being developed by some people for the terminal.
