### ISSUE TITLE
[FEATURE] Will there be a fullbody tracking support ?

### ISSUE THREAD

**Issue by WinteruOfficiel** [DaXcess/LCVR#136]
I understand that it might not be the highest priority, but is there a plan for it? Are there any technical challenges hindering its implementation?

thanks for reading

**Comment by bavninja** [comment]
Main technical limitation to this would be the lack of full body tracking in the developers setup. Without this it's very difficult to implement as it requires tons of testing

**Comment by WinteruOfficiel** [comment]
you mean fullbody riging on the player model ?

**Comment by bavninja** [comment]
No just like the whole motion tracking setup

**Comment by DaXcess** [comment]
FBT will not be added to LCVR (unless an external contributor adds it).
