### ISSUE TITLE
Upscaling settings breaks rendering 

### ISSUE THREAD

**Issue by wasikuss** [DaXcess/LCVR#16]
When changed settings related to upscaling to *true* causes right eye display frozen portion of UI on black background. Left eye displays correct view.

```
[Performance]
EnableUpscaling = true
EnableDLLS = true
```

**Comment by DaXcess** [comment]
Fixed in 42eeb9bf35e88dd6b64d38626ea890e73027b295, also only appeared to be caused by DLSS, "normal" upscaling seemed fine
