### ISSUE TITLE
Animations Don't work

### ISSUE THREAD

**Issue by MalacoX** [DaXcess/LCVR#160]
I installed the VR mod with a couple of my  friends (2 in vr and 3 on pc) and for some reason all animations are broken and its just a still pose... (I am using a mod-pack so it might be that but it still is a bug soooo... Here's the code: 018d290a-dd36-c07c-6e96-86beb25f2ff9)

**Comment by PKFye** [comment]
Having the same issues. Can't see my arms move.

**Comment by helluvanidiot** [comment]
same here. The player remains still in the default pose constantly

**Comment by bavninja** [comment]
Did you look at compatibility list? remove moreemotes and it will work most likely checked for 1 second and removed profile agian
