### ISSUE TITLE
Profiles for detected controllers are not downloaded unless manually overridden

### ISSUE THREAD

**Issue by Phil25** [DaXcess/LCVR#168]
### Overview
I'm _assuming_ that controllers which are now automatically detected and their profile name selected by LCVR are supposed to be downloaded **without** users providing an override themselves. This is currently not the case.

Tested on `1.1.0` but it doesn't seem `1.1.1` addressed this.

### Repro

1. Use Valve Index and confirm its controller profile is detected.
   `[Info   :      LCVR] Detected controllers, applying controller profile 'index'...`
2. Do not provide custom overrides for profiles.
3. Make sure the LCVR version (1.1.0 and 1.1.1 both) does not support Index controllers.
   `[Warning:      LCVR] Tried to load unknown controller profile: index, falling back to default`
4. Make sure `index` profile is present on the remote repo (for debugging purposes I switched to my fork and branch).
5. Observe that the profile is not downloaded (I dunno how but I added a bunch of logs).

### Inspection (comments mine)
In `Actions.cs` there's this bit of code:
```cs
if (!DetectControllerProfile(out var profile))
{
    /* snip, assume above function succeeds */
}

Plugin.Config.LastInternalControllerProfile.Value = profile;
allActions = GetProfile(profile); // profile is `index`
```

Then later on:
```cs
private static InputActionAsset GetProfile(string profile)
{
    if (!profiles.TryGetValue(profile, out var inputAsset))
    {
        Logger.LogWarning($"Tried to load unknown controller profile: {profile}, falling back to default");
        inputAsset = profiles["default"];
    }

    // `Plugin.Config.ControllerBindingsOverrideProfile.Value` IS null
    var actions = string.IsNullOrEmpty(Plugin.Config.ControllerBindingsOverrideProfile.Value) switch
    {
        true => inputAsset, // default profile is always used
        false => DownloadControllerProfile(Plugin.Config.ControllerBindingsOverrideProfile.Value, out var downloadedAsset) switch
        {
            true => downloadedAsset,
            false => inputAsset
        }
    };

    return actions;
}
```

Since an override was not provided, autodetected controllers will never have their profile downloaded.

The simplest fix I found would be to treat the detected controller profile as an override itself to force the download, ex:
```diff
  if (!DetectControllerProfile(out var profile))
  {
      /* snip */
  }
+ else if (string.IsNullOrEmpty(Plugin.Config.ControllerBindingsOverrideProfile.Value))
+ {
+     Plugin.Config.ControllerBindingsOverrideProfile.Value = profile;
+ }
  
  Plugin.Config.LastInternalControllerProfile.Value = profile;
```

Which is what I'm currently doing for testing, but not sure if it doesn't have any side effects yet. The "unknown controller profile" warning message could also be reworded since it's a bit misleading.

**Comment by Phil25** [comment]
If the suggested fix is fine I'll push a PR, let me know if this is the intended way tho.

**Comment by DaXcess** [comment]
This is intended behavior, as the controller detection will grab profiles that are inside the mod itself (not those inside the LCVR-Controller-Profiles repo). Currently it says "unknown profile" as there are no bindings for the index yet (both in the mod and in the profiles repo).

The only ones that are currently embedded in the mod (internal profiles) are `default` and `htc_vive`.

**Comment by Phil25** [comment]
I see, I thought autodetected profiles should take precedence and be downloaded regardless. What would it take to add `index` profile other than editing `LCVR-Controller-Profiles`? Just adding a new entry to `profiles` is enough?

I'm currently working on the former, but it'd prolly take me some trial and error to get it working :P

**Comment by Phil25** [comment]
I wanted to avoid installing Unity but I guess it's the simplest way to do this. In any case, I'm gonna close this issue since it's not a bug.

**Comment by DaXcess** [comment]
> I wanted to avoid installing Unity but I guess it's the simplest way to do this. In any case, I'm gonna close this issue since it's not a bug.

FYI it can still be done via JSON, it's only a different extension, and I replaced the JSON manual for the Unity manual as for others it's easier to work with.

**Comment by Phil25** [comment]
Took me a bit to understand what was going on and the fact that the json files were no longer needed, but tests seems to confirm that https://github.com/DaXcess/LCVR-Controller-Profiles/pull/31 is working.
