### ISSUE TITLE
Weird arms like their bones have been broken

### ISSUE THREAD

**Issue by Speedymule6858** [DaXcess/LCVR#169]
I found an issue I am using Quest 2 with virtual desktop on versions 1.10 and above there is a weird arm tracking the only way I can describe it makes it look like my bones have been mangled and it annoys me while I play the only work around right now is to use version 1.01

**Comment by Altived** [comment]
aware, it is a bug which really isnt that annoying so it is just a skill issue for you rn

**Comment by DaXcess** [comment]
Fixed on `dev`
