### ISSUE TITLE
Index Input Loss (1.1.3)

### ISSUE THREAD

**Issue by Waffles5536** [DaXcess/LCVR#170]
Since 1.1.3, I have experienced massive losses in input functionality. Namely: Jump, Hotbar selection, Menu, Primary Use, Drop, and crouch buttons no longer work. Unaware if more exist, but the issue makes the game unplayable on index controls.

**Comment by DrunkOnSuccess** [comment]
I have lost use of the right trigger.

**Comment by Phil25** [comment]
This can be closed, it's solved for 1.1.4.

**Comment by DrunkOnSuccess** [comment]
Not by default, you have to go into the config and change "ControllerBindingsOverrideProfile" to "index"

**Comment by Phil25** [comment]
> Not by default, you have to go into the config and change "ControllerBindingsOverrideProfile" to "index"

1.1.3 had its own set of issues.

**Comment by DrunkOnSuccess** [comment]
> > Not by default, you have to go into the config and change "ControllerBindingsOverrideProfile" to "index"
> 
> 1.1.3 had its own set of issues.

Good for.. 1.1.3? This issue exists on 1.1.4, the input still has to be enabled in config.

**Comment by Phil25** [comment]
That's not what this issue in particular is about. Though it's good to let them know.

**Comment by DrunkOnSuccess** [comment]
> That's not what this issue in particular is about. Though it's good to let them know.

Honestly with the mess of control issues between 1.1.0 and 1.1.4 I wouldn't be surprised if it was a same or similar fix in the end, although yeah my bad, didn't see the "1.1.3" in the title of the issue.
