### ISSUE TITLE
Trigger doesn't work as ActivateItem on Index (1.1.4)

### ISSUE THREAD

**Issue by josephowen** [DaXcess/LCVR#174]
All the controls I have tried work except left trigger for ActivateItem (e.g. to toggle the flashlight).

Curiously, I _am_ able to toggle the flashlight by squeezing the right grip (Interact) and then using SwitchItem. The flashlight only toggles its light as I switch off of it, but squeezing the right grip beforehand is required for that to happen. I tried removing any other mods that could possibly interact, and made sure to reset to the default controller bindings in SteamVR, so I don't think this is an issue with my configuration. It was working fine last time I played (Jan 13th, so presumably v1.0.0).

The finger tracking works for the right index finger, so it is definitely detecting my trigger pull, just not mapping that to ActivateItem.

**Comment by Phil25** [comment]
Can you link your BepInEx logs? It could be detecting your controllers wrong.

Try to launch the game with SteamVR already open already, it helps with controller support. Otherwise, see if manually overriding `ControllerBindingsOverrideProfile` to `index` in the mod config works.

**Comment by FEFELAND** [comment]
@Phil25  Thank you very much, saved my play session there. Had the same issue but manually setting "index" on the controller override made it work again.

**Comment by josephowen** [comment]
Manually setting "index" worked for me too. Previously, I was launching the game with SteamVR open already, but that wasn't sufficient. Manually overriding `ControllerBindingsOverrideProfile` was apparently necessary.
