### ISSUE TITLE
Shaking/lagging and FOV issues with certain runtimes

### ISSUE THREAD

**Issue by DaXcess** [DaXcess/LCVR#177]
I myself have only been able to reproduce it on my Quest 2 by using Airlink **and** using SteamVR as the runtime. My best description of the issue is: it looks like the FOV gets manipulated by the direction the headset is moving in, like some sort of motion prediction which fails miserably inside the runtime(s).

It is unclear if this is caused by the Oculus runtime, the SteamVR runtime, or by both (aka both runtimes are modifying the resulting image/tracking data which is warping perspective).

I have absolutely **zero** clue as to why this is happening. The only thing I can think of is some kind of motion prediction which is not working at all. This is with ASW disabled on the Oculus side too.

**Comment by nicklllmedia** [comment]
Can you tell which GPU are you using. I had some similar issues with just 8Gb VRAM on board. Running Oculus Home, SteamVR Home and the game struck at VRAM limit in no time, causing all of my system to lag. You can simply tell if it is so if you get up to 6.5-7Gb VRAM usage without game boot up.

**Comment by DaXcess** [comment]
NVIDIA RTX 2070, but still doesn't make sense why the **combination** of Oculus + SteamVR causes this, even though using something like VDXR already maxes out my GPU but that one does not trigger it (nor using Oculus or SteamVR without any other runtimes in between)

**Comment by lukis101** [comment]
While I'm not on best setup for testing this issue due to being on quite old OVR runtime (Jun 22, 2022) with Rift CV1, was observing same behavior even in a minimal unity project and pavlov (which is UE5 OpenXR).

I've narrowed it down to be issue with OVR **when SteamVR is used as the OpenXR runtime and 'Depth Submission Mode' is 24bit**. Using 16bits seems to be the workaround and verified by changing to 16bits in local mod build:
https://github.com/DaXcess/LCVR/blob/06550ccc07f4a1911efa53ef15659e660066deff/LCVR/Plugin.cs#L310

**Comment by DaXcess** [comment]
> While I'm not on best setup for testing this issue due to being on quite old OVR runtime (Jun 22, 2022) with Rift CV1, was observing same behavior even in a minimal unity project and pavlov (which is UE5 OpenXR).
> 
> I've narrowed it down to be issue with OVR **when SteamVR is used as the OpenXR runtime and 'Depth Submission Mode' is 24bit**. Using 16bits seems to be the workaround and verified by changing to 16bits in local mod build:
> 
> https://github.com/DaXcess/LCVR/blob/06550ccc07f4a1911efa53ef15659e660066deff/LCVR/Plugin.cs#L310

Can confirm this. This combined with the fact that **this wasn't doing anything anyways** means that I will be setting this to `None` in the next update, fixing the issue.

**Comment by sdrawkcaBsIsihT** [comment]
disabling snap/smooth turning in lcvr configs allowed me to move my head normally without the feeling of someone violently shaking me when attempting to move it. Its obviously not the best solution if you are going to use those settings
