### ISSUE TITLE
[Enchancement] EVEN MORE improved interactions

### ISSUE THREAD

**Issue by 1nfameArts** [DaXcess/LCVR#179]
- Keyboard being pressable by pushing them with your arms (immersive type of typing)
- Move item to the coil to charge it (if its chargable)
- Swinging your arms makes you run
- Crouching IRL will make your ingame character crouch
- Decrease mic volume to 25% by covering your mouth [(Yoinking ArcticFox037's idea to put it here)](https://discord.com/channels/1192754217564254238/1198376752964173967)
This will be all healthy for roomscale players.

**Comment by MrchubbyBub** [comment]
these are all amazing features and the crouching one is already in the game.

**Comment by DaXcess** [comment]
1. Requires custom models, and I ain't a 3D artist.
2. Exists on `dev` branch
3. Requires complicated motion detection, something which I'm just not skilled in
4. Was added in 1.1.0
5. Exists on `dev` branch
