### ISSUE TITLE
Fog only renders in one eye whenever the ship radar is active

### ISSUE THREAD

**Issue by NickHam13** [DaXcess/LCVR#189]
Moving this to GitHub where it will hopefully be easier to track

Currently, whenever the ship radar is active, the main volumetric plane only renders in the right eye for VR players. Usually this only happens while you're inside the ship but some mods keep the radar active all the time, which breaks the fog both outside and in the facility.

**Comment by DaXcess** [comment]
Identified where this happens.

For some reason, disabling the helmet model was causing this. Re-enabling the helmet model fixes the fog mismatch between the eyes. I don't know why this is the case, but it works. I do have to think about how to go about fixing this since this does add back the helmet model which limits FOV.

**Comment by NickHam13** [comment]
I can confirm this is now fixed with https://github.com/DaXcess/LCVR/commit/40e8251c0bf310e164b910d9c606a1347f016d37, but I won't close this until 1.1.8 is out. The helmet option is really cool as well, thanks.

**Comment by NickHam13** [comment]
Guess I'll use this issue to report, I think the helmet model has some issues, for example it lags behind your head movement very slightly. It also gets locked out of moving up and down sometimes, I think this is either related to leaving and rejoining a game or using the jetpack.

**Comment by DaXcess** [comment]
> Guess I'll use this issue to report, I think the helmet model has some issues, for example it lags behind your head movement very slightly. It also gets locked out of moving up and down sometimes, I think this is either related to leaving and rejoining a game or using the jetpack.

Prob easy fix by moving it around the hierarchy and setting it as a child of the gameplay camera so that it is 100% in sync with head movement

**Comment by DaXcess** [comment]
Quickly adding here that when you die the helmet gets positioned incorrectly, so upon death this bug returns. I have already got a fix ready locally which will be merged into 1.1.9
