### ISSUE TITLE
Can't Select Network Mode

### ISSUE THREAD

**Issue by YoloKouhai** [DaXcess/LCVR#19]
After running the game with the LCVR and BepInEx, the game boots in VR! However there is a purple square on the ground that moves weirdly and I am unable to select the network mode.  I play on Valve Index.

**Comment by AyOhEe** [comment]
I'm experiencing the same thing. Seems to be an issue with creating the necessary components for Unity's XR Interaction toolkit.

**Comment by ethanbradshaw** [comment]
Hey! I was experiencing this issue a few days ago, After following these steps earlier today the mod worked perfectly for me, I believe that the Unity DLL's on the github dont really work so you need to get them yourself from a fresh unity project. 
![VRSETUP](https://github.com/DaXcess/LCVR/assets/65248093/acadc9b5-ce51-451e-ad2d-f39673a097bc)

**Comment by YoloKouhai** [comment]
I'll try it now!
