### ISSUE TITLE
Game crashes when using terminal after one day

### ISSUE THREAD

**Issue by ratsonmars** [DaXcess/LCVR#195]
I have no other mods enabled and for some reason after I land and then go back up whenever I use the terminal the game crashes.

**Comment by imaxHD** [comment]
Same issue new update completely breaks terminal

**Comment by imaxHD** [comment]
Best solution is the just revert to 1.1.6 until they realize the mod is unusable

**Comment by DaXcess** [comment]
This was fixed in 19b3917aa3a71bbd4364cc2c7c6c9462c1293e19 and dev version is available for download [here](https://github.com/DaXcess/LCVR/actions/runs/7745153229/artifacts/1212846991).

1.1.8 will drop later today on thunderstore
