### ISSUE TITLE
Valve Index Controls

### ISSUE THREAD

**Issue by YoloKouhai** [DaXcess/LCVR#20]
Valve Index controls appear to half work, I can drop things and interact with things but I cannot use the scanner or activate flashlights/items

**Comment by ethanbradshaw** [comment]
Trigger's currently don't work on index from the looks of it, someone on the Flat2VR discord is looking into creating a config to possibly resolve this, should know by tomorrow if it works or not

**Comment by NickHam13** [comment]
Fixed via https://github.com/DaXcess/LCVR/commit/9f79bd372a566aed5fce482966d947853a190afc

**Comment by YoloKouhai** [comment]
Closed it before testing cause I had faith, unfortunately it doesn't seem to work?

**Comment by NickHam13** [comment]
Are you building from the new-inputs branch? That's where the fix is

**Comment by YoloKouhai** [comment]
Yeah it's user-error, apologies! For some reason when I got a fresh download it didnt download the new-inputs!
