### ISSUE TITLE
TooManyEmotes restructure

### ISSUE THREAD

**Issue by cmooref17** [DaXcess/LCVR#200]
Hey, it's Flip from the TooManyEmotes mod. I restructured quite a bit of code with my mod, and will likely push it out tomorrow, or soon after. I know there were some compat patches with my mod, and this update will probably break most of them since a lot of methods you patched may not exist anymore. I already had logic for disabling emoting for self as a config option, which would help with VR compatibility, but it wasn't automatic, and it seems like your mod added patches for my mod anyways, but in my next update, I am automatically disabling emoting for yourself if this mod is enabled, so you should be fine removing the compat patches with my mod.

Just wanted to give a heads up in case people were asking why this mod was throwing errors about mine haha. But yeah, update should be pushed out tomorrow (2/11). We can also close this issue, too.

**Comment by DaXcess** [comment]
Hey there. Following up on this, I'm probably going to be removing the compatibility/patches on my end from 1.2.0 going forward, since it was pretty messy and hacked together (Prefixing a bunch of functions). A better way to handle compatibility would probably be done using the same idea that [BetterEmotes](https://github.com/KlutzyBubbles/lc-better-emotes/blob/main/BetterEmote/Compatibility/LCVRChecks.cs) had for their VR Compatibility, by basically checking for the LCVR mod (and it being in VR mode) and setting the disable model setting to true (without modifying the config file itself).

**Comment by cmooref17** [comment]
That basically how I added my compat fix, but I believe the mod was still in development, or maybe it was released recently, but at the time, I decided to have a manual toggle option for this. I want to say I was working with MantisGP to figure out the fix that needed to be applied, so he was very helpful. Not sure if you know them.

But yes, ideally, I will remove the config option and make it automatically patch when it detects that this mod is enabled.

I also wasn't able to push out the update yesterday, as I ran into some issues, but hopefully I can once I get back from work today. Fingers crossed!

I'll let you know if anything changes, though

**Comment by cmooref17** [comment]
By the way, the update was pushed last night. I also don't even touch the player's animator anymore. I use a sepearate one, but either way, I should be disabling all emoting for the local player, and emote menu stuff when LCVR is installed. If someone says that I created another issue, it was probably a goof on my part, but if you let me know, I can quickly fix it.

You should be good to close this once you read it!

**Comment by DaXcess** [comment]
Looks good, haven't had any reports (except for users using wrong versions).
Only problem I see is that when LCVR is loaded the entire emote mod just disables itself, even when the user is not using VR, making the patch somewhat useless.

**Comment by DaXcess** [comment]
Here's the issue for reference: https://github.com/cmooref17/Lethal-Company-TooManyEmotes/issues/65
