### ISSUE TITLE
Bug: when joining a lobby the game freezes and crashes

### ISSUE THREAD

**Issue by DmitriyRyazanovsky** [DaXcess/LCVR#202]
When I connect to players, I can only play for a while, after which the program freezes

There is no such problem when disabling the mod

System:
Windows10
rtx 3060
intel i5-12100f
16gb 3200ram

VR:
Oculus Quest 2

**Comment by bavninja** [comment]
What runtime are you using?

**Comment by bavninja** [comment]
And are there other mods enabled?

**Comment by DonorMozga** [comment]
> And are there other mods enabled?

Yes, of course, I did everything according to the instructions

![image](https://github.com/DaXcess/LCVR/assets/45229909/2675cce5-24d5-4f85-8a7d-13a211674868)

**Comment by DonorMozga** [comment]
> What runtime are you using?

I connect the computer to my glasses, then I just launch the game through the launcher with a VR mod and put on the glasses, then the game launches itself and I play it

**Comment by bavninja** [comment]
try using another runtime to launch the game

**Comment by DonorMozga** [comment]
> try using another runtime to launch the game

Which one would you recommend?

**Comment by bavninja** [comment]
What are you using currently?

**Comment by DonorMozga** [comment]
> What are you using currently?

r2modman

**Comment by bavninja** [comment]
openxr runtime ;) oculuslink, steamlink, VD

**Comment by DonorMozga** [comment]
> openxr runtime ;) oculuslink, steamlink, VD

Oh, sorry, i am use oculuslink

**Comment by bavninja** [comment]
Developer uses VD so thats what I would recommend, however this is a paid software. so maybe try steamlink first as a runtime can have a big influence on this type of glitches

**Comment by DonorMozga** [comment]
> openxr runtime ;) oculuslink, steamlink, VD

I will try steamlink for start

**Comment by DmitriyRyazanovsky** [comment]
I figured out what's wrong

Since I live in Russia, my oculus has not been updated for a year (I had version 42), now it’s version 60

**Comment by DmitriyRyazanovsky** [comment]
Here is a guide on how to update oculus in Russia

Here is the update guide:
1) Uninstall all firmware (even if oculus is new, you still need to uninstall the firmware and block access to the location)
2) Roll out the update through a router with a VPN installed on it (if you install a VPN on your phone and distribute the Internet through it, the oculus somehow determines that you are in Russia and blocks access forever, so this will not work)
3) To update again, you need to do the whole procedure again


Вот гайд по обновлению: 
1) Снести всю прошивку (даже если oculus новые, всё равно надо снести прошивку и заблокировать доступ к местоположению) 
2) Накатить обновление через роутер с установленным на него ВПН (если уcтановить ВПН на телефон и раздать интернет через него, окулусы как-то определяют что ты в россии и блокируют доступ навсегда, поэтому так не получится)
3) Всё, чтобы снова обновиться, нужно проделать всю процедуру заного
