### ISSUE TITLE
Scroll not working on 1.9.0

### ISSUE THREAD

**Issue by metelkoww** [DaXcess/LCVR#205]
when we update the mod we have bug with scroll items and scroll pages in terminal, when we reinstall the mod to version 1.8.6 scroll start to working again

**Comment by DaXcess** [comment]
LCVR does not have a version 1.9.0 **or** 1.8.6?

**Comment by metelkoww** [comment]
xd sorry it was not in there, I was writing to mod developer wtf

**Comment by DaXcess** [comment]
Confirmed bug in [TooManyEmotes](https://thunderstore.io/c/lethal-company/p/FlipMods/TooManyEmotes/changelog/), not an LCVR issue
