### ISSUE TITLE
Fog Only Appears in One Eye

### ISSUE THREAD

**Issue by YoloKouhai** [DaXcess/LCVR#21]
Self explanatory, fog and lights and such only appear in the left eye, causing me to need to turn off Volumetrics.

**Comment by AyOhEe** [comment]
Seems to be post-process in general having issues with stereo rendering. I'll dig into this tomorrow and see if I can find any leads.

**Comment by NickHam13** [comment]
Seems to be fixed as of https://github.com/DaXcess/LCVR/commit/330c5a65eed11932d29d0c4799c9641d3dd1296c
