### ISSUE TITLE
Models visible to yourself when using any modelreplacementapi player model.

### ISSUE THREAD

**Issue by hgfdswer22** [DaXcess/LCVR#211]
as said. the models are visible to you (so if the model has a big head, all you will see is the inside of the head.).

are they incompatible? if they are, then why isn't it on the compatibility list?

**Comment by DaXcess** [comment]
ModelReplacementAPI is incompatible and wasn't tested enough (at all?) so it wasn't added to the compatibility list.

Lethal Company has many mods, and we're not going to check every single one for compatibility with VR, so the list is never 100% complete. Updates to the list come from user reports, without user reports, mods do not get added.
