### ISSUE TITLE
Lethal Progression "Upgrades" Tab Doesn't Exist In The VR Pause Menu

### ISSUE THREAD

**Issue by GoldenWerewolf112** [DaXcess/LCVR#220]
I Just Want To Know If You Can Make A Patch For It Or Does The Patch Have To Be From The Lethal Progression Dev HimSelf ?

Thanks For Reading, I Await Your Response 😗

**Comment by DaXcess** [comment]
This sounds like something on their end, since the pause menu in VR is basically a 1:1 flatscreen representation of the pause menu, but placed in world space.

**Comment by GoldenWerewolf112** [comment]
Ok Thank You Very Much For Your Response I Hope You Have A Wonderful Rest Of Your Day or night depending on the time you read this message 😁
