### ISSUE TITLE
Fails to move camera with player is ejected into space

### ISSUE THREAD

**Issue by EliAgne** [DaXcess/LCVR#221]
When failing to meet quota, the player is ejected into space. While using this mod, the camera almost always fails to move with the player once ejected. I have seen this work once during 40+ hours of using this mod. 

I am using a steam index.

**Comment by DaXcess** [comment]
Can't seem to reproduce this issue, so it's either caused by another mod, or has already been fixed on the `dev` branch (which is what I exclusively use). If it's the latter, then v1.2.0 will fix the issue.

**Comment by EliAgne** [comment]
Confirmed fixed by v1.2.0.
