### ISSUE TITLE
The game wont load in my VR

### ISSUE THREAD

**Issue by VRaptorYT** [DaXcess/LCVR#222]
So I have been working FOREVER to make this mod work, and this message keeps coming up, is it because I'm on the Quest Three, or would it be because of my PC? Does anyone know how to fix it?
![Screenshot 2024-03-14 172557](https://github.com/DaXcess/LCVR/assets/163475098/308e9ba5-57ce-48af-90eb-4d9d842f2e7d)

**Comment by DaXcess** [comment]
> This generally means that your headset is not connected, or that your headset is connected to a different runtime. Please make sure your headset is active and connected, and that you are using the correct OpenXR runtime.

According to the warning, your headset must be connected **and active** using **Oculus (air)link** for it to work.

**Comment by VRaptorYT** [comment]
Yeah, it is active and connected through a USB-C cord but it just won’t load into my headset. Is there a possibility it’s just my computer, or is there a app I have to get?

**Comment by DaXcess** [comment]
If all setup is done correctly and it still gives the error "XR_ERROR_FORM_FACTOR_UNAVAILABLE" then I'm guessing it also doesn't work for other games, since that error is coming from "Oculus OpenXR" (in your case), and not from LCVR.

**Comment by VRaptorYT** [comment]
Ohhhhhh ok. Is there any way I can fix that? I'm currently on Windows 11 Home btw

**Comment by DaXcess** [comment]
No clue tbh, I don't use the Oculus software myself

**Comment by inconvenient-Code** [comment]
Try to start up Lethal Company in non-VR and open up the VR settings menu at the right of the menu screen. Change your Runtime to SteamVR (this is the first option you will notice) and that should (hopefully) solve your issue.
Quest itself is a bit of a pain, so i always run my games through SteamVR AND (wired) Quest Link.

Hope that works for you, by the looks of it, the issue is more than likely as simple as this :)

**Comment by VRaptorYT** [comment]
Do I run the game on modded or non modded?

**Comment by inconvenient-Code** [comment]
I used modded, although you can always test in Vanilla incase mods are conflicting one another. It has compatibility between Vanilla and Modded as far as i am aware.

**Comment by VRaptorYT** [comment]
I tried running it and I changed my runtime to Oculus OpenXR because SteamVR wasn't there. Every time I try connecting SteamVR to my headset it says the graphics card is outdated, even though I have a Windows 11. But my computer is also acting like it's not connected to my headset, and I'm not sure why. Sorry for typing all of this confusing stuff lol

**Comment by VRaptorYT** [comment]
![Screenshot 2024-03-23 203834](https://github.com/DaXcess/LCVR/assets/163475098/5e6a755b-f03b-4bf4-a2b7-995203b3e9c4)
It says this when I try using SteamVR

**Comment by VRaptorYT** [comment]
Nevermind, I got it to work!
