### ISSUE TITLE
[Compatibility] Fixing ModelReplacementAPI models rendering in first person. 

### ISSUE THREAD

**Issue by BunyaPineTree** [DaXcess/LCVR#223]
Hello, this is the ModelReplacementAPI developer. I recently received a bug report relating to model replacements rendering in first person while using LCVR. 
Unfortunately that is not something I can fix, or even test, for that matter, but I have two leads on what might be causing it which should be fairly simple to identify and fix. 

The first possibility is the cullingmask used by your first person camera. 
I render models on the layers 23 and 17, which most cameras should render with the exception of the first person camera. 
Note that I directly manage the first person camera's cullingmask to remove those layers and to ensure compatibility among several camera mods, and so this is the very first thing that I thought of.

The second possibility has to do with a null reference exception related to TooManyEmotes that was also reported to me. 
To explain what is going on, I have a script `ViewStateManager` that runs the method `GetViewState()` on update to determine whether the current view state is first person, third person or otherwise to handle rendering. 
One of the checks I run in `GetViewState()` is, 

"If TooManyEmotes exists, and the TooManyEmotes emote camera is active, render in third person mode" 

I am uncertain what could be causing this, but it seems that when LCVR is put in flatscreen mode this returns an error. This may unintentionally result in it processing the viewstate as third person, which would also result in the model replacement rendering while in first person. 

As the only code involved is:

`private bool DangerousTMEViewState() => ThirdPersonEmoteController.emoteCamera.enabled;`

And this code only runs when `"FlipMods.TooManyEmotes"` is present in the chainloader, I'm fairly confident that it's not a bug that I accidentally let slip through the cracks.

Anyways if there is anything you need from me please let me know. My intuition tells me that it is simply a culling mask issue, but if it becomes more complicated than that I can see what I can do on my end as well.

**Comment by DaXcess** [comment]
For the TME part, I can confidently say it is being caused by TME optimistically disabling itself when LCVR is present, and I would guess that this causes `emoteCamera` to be `null`, so adding an extra `null` check would fix the TME errors.

LCVR doesn't normally manipulate the gameplay camera itself. It only switches off the UICamera (used for the camera stacking within LC) and optionally if a specific command line argument is provided, it adds layer 11 to the culling mask (which will make all colliders visible).

**Comment by cmooref17** [comment]
Hello! Would it be helpful if I initialized the emote camera, even if LCVR is enabled? It honestly wouldn't hurt anything since there are more checks to prevent switching to the emote camera anyways if LCVR is enabled.

**Comment by BunyaPineTree** [comment]
No I don't believe there is any need to. 

The original reporter of the bug actually did me a huge favor and confirmed that the model rendering in first person does not occur when TME is not installed, so the issue was that null reference rather than culling mask nonsense, which was what I originally believed it to be.

I'll go with DaXcess's excellent advice to perform a null check and mark this as resolved. 
Thanks for the help.
