### ISSUE TITLE
Jetpack unusable at high speeds in v1.2.0

### ISSUE THREAD

**Issue by Kylew1992** [DaXcess/LCVR#224]
Using Valve Index.
Not sure if this was an intentional change or just a side effect of all the changes that were made between v 1.1.9 and v 1.2.0.
In the 1.1.9 clip I don't take damage when easing off the thruster at high speeds. (Not sure why no Audio)
In the 1.2.0 clip I take damage upon takeoff and every time you ease off the thruster while at high speeds.

https://github.com/DaXcess/LCVR/assets/16767835/efcffea3-5680-480e-b6fc-8bbc026db7cf

https://github.com/DaXcess/LCVR/assets/16767835/6c8f50f7-1316-48ef-b868-67e240eadd30

**Comment by DaXcess** [comment]
The Jetpack is considered incompatible with VR and is only still usable because blocking it's usage seemed unfair to do.
The changes made by v1.2.0 definitely caused it, but this will not be fixed unless a dedicated update to fix the Jetpack somehow becomes a thing.
