### ISSUE TITLE
General performance issues

### ISSUE THREAD

**Issue by AxilotlX** [DaXcess/LCVR#227]
Completely unable to play LCVR due to constant lag spikes, 1-5 FPS at most and regular crashing. I'm aware you need a good PC, and I have such, I was just wondering if there could be a performance update. What confuses me most is that the game worked perfect (30 FPS though) at V1.0.0, so it must have been some sort of update along the way causing this.

**Comment by bavninja** [comment]
A combination of mods can cause more lag, there are multiple performance mods out there that could help you fix some issues. Most used, CullFactory & AsyncLoggers
Others to load faster etc. BepInEx_Faster_Load_assetBundels_Patcher & Loadstone
