### ISSUE TITLE
Hands stuck above head

### ISSUE THREAD

**Issue by Garridan** [DaXcess/LCVR#228]
When I start the logs say my controllers connect successfully, and point and click actions work such as terminal or open cupboard. But when I pick up the clipboard I see it held at the very top right of my view (I also see my hands just floating above me in my shadow), and I'm unable to pull the lever or anything.

Tried disabling interaction settings but still can't pull lever, 
Idk what's going on. Also, default player height seems really short. But maybe thats just because I'm 6'6 😅

**Comment by bavninja** [comment]
emote mod ;)

**Comment by Garridan** [comment]
> emote mod ;)

That was a quick reply, thanks bud 🤗
