### ISSUE TITLE
Scaling issue

### ISSUE THREAD

**Issue by ReaperWasFatal** [DaXcess/LCVR#229]
Whenever I load into the game its always extremely zoomed in Ive tried fixing the scaling in steam vr itself and it still doesnt work. This is all I see when I load into it
![image_2024-04-16_113533538](https://github.com/DaXcess/LCVR/assets/167158618/f7e01251-8b37-4154-b8bc-ff8f36cbaa1f)

**Comment by DaXcess** [comment]
If stuff breaks, always try and test with no other mods installed. They are 99.99999% of the time the cause.
