### ISSUE TITLE
Make Free Roam Spectating toggleable 

### ISSUE THREAD

**Issue by michaelstoel** [DaXcess/LCVR#234]
I really dislike it

**Comment by DaXcess** [comment]
The old spectating ability is gone, there is no way to get it back unless you play on 1.1.9 on earlier

**Comment by michaelstoel** [comment]
Thanks for the quick response!

That's unfortunate, especially on longer runs like 6-8 hours having those little breaks where you just watch the screen no need to control anything were nice.

**Comment by DaXcess** [comment]
While the flat screen spectating is gone, it indeed might be cool though if there's some kind of "sit back and do nothing" approach to the new system. At least the purely flat surface alone like before is not something I want to have, but something that like follows the spectated player might be cool.

**Comment by AmeliaGL0w0** [comment]
maybe a setting that allows you to go back to the screen from before 1.2.0 would be a solution to this issue
