### ISSUE TITLE
Shovel tools and spray paint are not available in v50

### ISSUE THREAD

**Issue by Heihei6732** [DaXcess/LCVR#235]
Shovel tools and spray paint are not available in v50, the device is Meta Quest2, Mod version is 1.2.2

**Comment by DaXcess** [comment]
You are not going to believe this

![image](https://github.com/DaXcess/LCVR/assets/46288749/da13057e-fd71-4db6-89e3-671b463d8db2)

**Comment by Heihei6732** [comment]
![1](https://github.com/DaXcess/LCVR/assets/118957642/e5fc8333-7372-4b34-969f-543b5d08ac47)
look,I can't use it over my shoulder

**Comment by DaXcess** [comment]
Remove unsupported mods, LCVR has no issues on it's own

**Comment by Heihei6732** [comment]
I removed all the mods, kept only LCVR, started the game again, and found that I still couldn't use the shovel

**Comment by Heihei6732** [comment]
这个问题跟串流软件有关联吗，我使用的是Virtual Desktop

**Comment by Heihei6732** [comment]
Is this problem related to streaming software? I'm using Virtual Desktop

**Comment by DaXcess** [comment]
This is a problem with your game then (or still hidden mods), since nobody using LCVR on V50 is experiencing this issue

**Comment by Heihei6732** [comment]
I formatted my computer's hard drive, reset the system, re-downloaded the game and installed LCVR and found that I still couldn't use the shovel attack

**Comment by Heihei6732** [comment]
Pick up the shovel Is the shovel held with both hands by default? or do you need to press the button on the handle of the left hand

**Comment by Heihei6732** [comment]
I found a guy in my group chat who had the same problem as me, who could only hold a shovel with one hand and couldn't attack, and his device was a PICO 4

**Comment by DaXcess** [comment]
You cannot use the trigger to make the shovel attack, it requires motion

**Comment by Heihei6732** [comment]
I raised the shovel over my shoulder and swung it out, it didn't work, my shovel could only be held with one hand, and physical shaking of the spray paint didn't work

**Comment by DaXcess** [comment]
Then something is still broken even after resets. Anyways without logs this is impossible to figure out for me.

**Comment by Heihei6732** [comment]
Where the log is located

**Comment by DaXcess** [comment]
<BepInEx folder location>\LogOutput.log

**Comment by Heihei6732** [comment]
[LogOutput.log](https://github.com/DaXcess/LCVR/files/15105667/LogOutput.log)

**Comment by DaXcess** [comment]
There are several mods present which I cannot verify the compatibility of as they're not available on Thunderstore (or at least not under the names shown in the log)

**Comment by Heihei6732** [comment]
Only LCVR and the language pack were added, with no other modules

**Comment by Heihei6732** [comment]
![image](https://github.com/DaXcess/LCVR/assets/118957642/189566a0-f191-42e7-94a0-a413b7b51127)
****

**Comment by DaXcess** [comment]
I'd suggest using checking if the issue is still present with only LCVR and BepInEx installed. That language mod has a lot of invasive patches on certain objects.

**Comment by DaXcess** [comment]
In fact, I'm 99% certain it's the language mod since LCVR requires the english names to attach the special VR scripts to the items
https://github.com/DaXcess/LCVR/blob/8b14d6df05d487859800f9b138f2ef2a4b17e029/Source/Player/Items.cs#L10-L19

**Comment by Heihei6732** [comment]
Deleting language packs can now use a shovel, but I see other people using language packs can also use a shovel
![image](https://github.com/DaXcess/LCVR/assets/118957642/e70eb2cc-5456-4c86-9098-768c15d3a2e8)

**Comment by Heihei6732** [comment]
![image](https://github.com/DaXcess/LCVR/assets/118957642/48c3b206-d30a-434a-9202-75a5645fba74)
Will this input work

**Comment by DaXcess** [comment]
I don't know, I have no idea how the translation mod works

**Comment by Heihei6732** [comment]
![VirtualDesktop Android-20240425-172656](https://github.com/DaXcess/LCVR/assets/118957642/cb09b03e-e0aa-47e1-b6d9-70eab005a1f1)
It turns out it works
