### ISSUE TITLE
[Bug] Snare Flea remains stuck to player's face in death spectate mode when dying from fall damage

### ISSUE THREAD

**Issue by Welcius** [DaXcess/LCVR#236]
Game Version: v50
LCVR Version: v1.2.2

I am fairly new to the game so I do not have the skill to reproduce this, but I did jump into a facility free-fall pit to kamikaze kill a Snare Flea when it attacked me and it kept stuck on my face on the death spectate camera until I respawned again in orbit  (I assume this is LCVR related). The teammates that were dead as well told me that from their POV I did not have it still on my face, logically.

**Comment by DaXcess** [comment]
If you remember exactly what the state of your team was (how many players alive, how many players dead before you died, etc) then I can narrow it down even more. If I can then still not reproduce it it's either random, or another mod that did some interfering.

**Comment by DaXcess** [comment]
Issue has become stale, I'm closing this for now
