### ISSUE TITLE
OpenXR issue

### ISSUE THREAD

**Issue by Propain287** [DaXcess/LCVR#237]
Im trying to use the mod with my oculus quest 2 which wouldn't be a problem IF every time I run the game I get the same issue
----------------------------------------
[Error  :      LCVR] Failed to start in VR Mode! Only Non-VR features are available!
[Warning:      LCVR] Runtime Name:    <Missing>
[Warning:      LCVR] Runtime Version: <Missing>
[Warning:      LCVR] Last Error:      XR_ERROR_FILE_ACCESS_ERROR
[Warning:      LCVR]
[Warning:      LCVR] Unknown reason for OpenXR failure!
[Warning:      LCVR]
==== OpenXR Init Info ====

Stage 1 Missing Entry Points: (1)
  xrInitializeLoaderKHR

==== OpenXR Provider Info ====

Spec Version: 1.0.27
Provider Version: 1.8.2
App: Lethal Company #3159629941
Engine: 2022.3.9f1 #53515265

==== OpenXR Runtime Info ====

Features requested to be enabled: (7)
  : Version=, Company=""
  : Version=, Company=""
  : Version=, Company=""
  : Version=, Company=""
  : Version=, Company=""
  : Version=, Company=""
  : Version=, Company=""

Requested feature extensions not supported by runtime: (0)

Available Runtime Extensions: (31)
  XR_KHR_D3D11_enable: Version=9
  XR_KHR_D3D12_enable: Version=9
  XR_KHR_opengl_enable: Version=10
  XR_KHR_vulkan_enable: Version=8
  XR_KHR_vulkan_enable2: Version=2
  XR_KHR_composition_layer_depth: Version=6
  XR_KHR_win32_convert_performance_counter_time: Version=1
  XR_KHR_convert_timespec_time: Version=1
  XR_KHR_composition_layer_cube: Version=8
  XR_KHR_composition_layer_cylinder: Version=4
  XR_KHR_composition_layer_equirect: Version=3
  XR_KHR_visibility_mask: Version=2
  XR_KHR_composition_layer_color_scale_bias: Version=5
  XR_EXT_win32_appcontainer_compatible: Version=1
  XR_EXT_debug_utils: Version=5
  XR_OCULUS_recenter_event: Version=1
  XR_OCULUS_audio_device_guid: Version=1
  XR_FB_color_space: Version=3
  XR_FB_display_refresh_rate: Version=1
  XR_META_performance_metrics: Version=2
  XR_META_headset_id: Version=1
  XR_OCULUS_ovrsession_handle: Version=1
  XR_EXT_local_floor: Version=1
  XR_EXT_active_action_set_priority: Version=1
  XR_FB_haptic_amplitude_envelope: Version=1
  XR_FB_haptic_pcm: Version=1
  XR_FB_touch_controller_pro: Version=1
  XR_META_touch_controller_plus: Version=1
  XR_FB_touch_controller_proximity: Version=1
  XR_OCULUS_external_camera: Version=1
  XR_META_detached_controllers: Version=1

Available Layers: (1)
  XR_APILAYER_reshade: SpecVersion=1.0.0, LayerVersion=2, Description="crosire's ReShade post-processing injector for 64-bit"

Available Runtime Layer Extensions: LayerName="XR_APILAYER_reshade": (0)

==== Last 20 non-XR_SUCCESS returns ====
[FAILURE] xrCreateInstance: XR_ERROR_FILE_ACCESS_ERROR (1x)
[FAILURE] xrPollEvent: XR_ERROR_FUNCTION_UNSUPPORTED (1x)

==== Last 20 Events ====

[Warning:      LCVR] Failed to query runtimes: Could not find a part of the path "D:\Oculus\Support\oculus-runtime\oculus_openxr_64.json".
----------------------------------------
Now for short its basically looking for a Runtime for OpenXR in a place where it isnt. SO I move the openxr and the whole thing to my hardrive. BUT It gives this instead!
----------------------------------------
[Error  :      LCVR] Failed to start in VR Mode! Only Non-VR features are available!
[Warning:      LCVR] Runtime Name:    <Missing>
[Warning:      LCVR] Runtime Version: <Missing>
[Warning:      LCVR] Last Error:      XR_ERROR_RUNTIME_UNAVAILABLE
[Warning:      LCVR]
[Warning:      LCVR] It appears that no OpenXR runtime is currently active. Please go to the dedicated application for your VR headset and make sure that it is running, and set as default OpenXR runtime.
[Warning:      LCVR] Failed to query runtimes: Could not find file "C:\Program Files\Oculus\Support\oculus-runtime\oculus_openxr_64.json"
----------------------------------------
Its now looking for the runtime in the original FILE! and if I run both! it gives me this!
----------------------------------------
[Error  :      LCVR] Failed to start in VR Mode! Only Non-VR features are available!
[Warning:      LCVR] Runtime Name:    <Missing>
[Warning:      LCVR] Runtime Version: <Missing>
[Warning:      LCVR] Last Error:      XR_ERROR_FILE_ACCESS_ERROR
[Warning:      LCVR]
[Warning:      LCVR] Unknown reason for OpenXR failure!
[Warning:      LCVR]
==== OpenXR Init Info ====

Stage 1 Missing Entry Points: (1)
  xrInitializeLoaderKHR

==== OpenXR Provider Info ====

Spec Version: 1.0.27
Provider Version: 1.8.2
App: Lethal Company #3159629941
Engine: 2022.3.9f1 #53515265

==== OpenXR Runtime Info ====

Features requested to be enabled: (7)
  : Version=, Company=""
  : Version=, Company=""
  : Version=, Company=""
  : Version=, Company=""
  : Version=, Company=""
  : Version=, Company=""
  : Version=, Company=""

Requested feature extensions not supported by runtime: (0)

Available Runtime Extensions: (31)
  XR_KHR_D3D11_enable: Version=9
  XR_KHR_D3D12_enable: Version=9
  XR_KHR_opengl_enable: Version=10
  XR_KHR_vulkan_enable: Version=8
  XR_KHR_vulkan_enable2: Version=2
  XR_KHR_composition_layer_depth: Version=6
  XR_KHR_win32_convert_performance_counter_time: Version=1
  XR_KHR_convert_timespec_time: Version=1
  XR_KHR_composition_layer_cube: Version=8
  XR_KHR_composition_layer_cylinder: Version=4
  XR_KHR_composition_layer_equirect: Version=3
  XR_KHR_visibility_mask: Version=2
  XR_KHR_composition_layer_color_scale_bias: Version=5
  XR_EXT_win32_appcontainer_compatible: Version=1
  XR_EXT_debug_utils: Version=5
  XR_OCULUS_recenter_event: Version=1
  XR_OCULUS_audio_device_guid: Version=1
  XR_FB_color_space: Version=3
  XR_FB_display_refresh_rate: Version=1
  XR_META_performance_metrics: Version=2
  XR_META_headset_id: Version=1
  XR_OCULUS_ovrsession_handle: Version=1
  XR_EXT_local_floor: Version=1
  XR_EXT_active_action_set_priority: Version=1
  XR_FB_haptic_amplitude_envelope: Version=1
  XR_FB_haptic_pcm: Version=1
  XR_FB_touch_controller_pro: Version=1
  XR_META_touch_controller_plus: Version=1
  XR_FB_touch_controller_proximity: Version=1
  XR_OCULUS_external_camera: Version=1
  XR_META_detached_controllers: Version=1

Available Layers: (1)
  XR_APILAYER_reshade: SpecVersion=1.0.0, LayerVersion=2, Description="crosire's ReShade post-processing injector for 64-bit"

Available Runtime Layer Extensions: LayerName="XR_APILAYER_reshade": (0)

==== Last 20 non-XR_SUCCESS returns ====
[FAILURE] xrCreateInstance: XR_ERROR_FILE_ACCESS_ERROR (1x)
[FAILURE] xrPollEvent: XR_ERROR_FUNCTION_UNSUPPORTED (1x)

==== Last 20 Events ====

[Warning:      LCVR] Failed to query runtimes: An item with the same key has already been added. Key: Oculus OpenXR
----------------------------------------
So now its complaining about how there are two instances of the same file which makes sense! I went into the config to force it to run a certain openxr file the one in my C: but no matter what I did with the internal settings giving it the file location did nothing but spit out the first error where it looks for it in the other drive. Ive messed with it for 2 hours! but nothing. Ive ran steamvr as openxr ive done it all! ive messed with it in the game trying to change the openxr setting from system default to something else! but theres nothing but system default. 

Ive given up what I thought was a common problem turns out its only me! as my friend downloaded the same mod on the same version with the same mods as me! and he got it to work instantly! nothing was diffrent we have the same headset same oculus version same steamvr version! his just works and mine is broken! please help me DaXcess.

**Comment by Propain287** [comment]
Alright I do have reshade V6.1 installed for a mod for bonelab through occlus. How would I uninstall it?

**Comment by DaXcess** [comment]
I don't know, we don't provide generic OpenXR support here

**Comment by Propain287** [comment]
Alright it's just that I un-installed it on bonelab but it still didn't work gave the same error wo it must be installed somewhere else

**Comment by Propain287** [comment]
Hey so I uninstalled Reshade and the game and all but it still isnt working. I was wondering if there was a way to force run the runtime file?
