### ISSUE TITLE
User phasing through interior on specific moon

### ISSUE THREAD

**Issue by fnmeowskulls** [DaXcess/LCVR#239]
It always ended up in death, but it only seemed to happen to the one user of LethalCompanyVR, We were on the moon "Orion" and in both instances of death upon entering the Interior we had "CozyOffice" and "SCPFoundationDungeon" be the Interiors it happened in. Is it possible this happened due to the moon specifically, or the interiors in specific? Just reporting this strange issue, not sure anything might actually come out of it though.

this is the code we all were using (It's a little large though.)
018f7ab3-7434-5e61-b721-0ce7e61ce459

**Comment by DaXcess** [comment]
Can't reproduce. Since 1.2.0, VR also uses a new locomotion system which doesn't allow clipping out of bounds anymore, so this sounds more like a nonvr issue.
