### ISSUE TITLE
Rendering issue (Low FPS)

### ISSUE THREAD

**Issue by ToonLWind** [DaXcess/LCVR#241]
I use my quest 2 with quest link and steam vr, but the game runs so slow that it seems to be rendering on the quest itself. I cannot find anyway to make it render from my gpu.

**Comment by DaXcess** [comment]
Depending on your PC specs this is expected. The game resolution when playing VR is like 4x larger than when playing on monitor, and it's also getting rendered twice (one for each eye).
Also this mod doesn't touch rendering (it's all done by Unity), so there's nothing the mod can do to help.

**Comment by ToonLWind** [comment]
it was just using the oculus xr instead of the steam one. whoops!

**Comment by DaXcess** [comment]
Oh that works too lol

**Comment by Jackylacky162** [comment]
For anyone lese high bitrate set in oculus debug tool may also cause that
