### ISSUE TITLE
LCVR v1.3.0 (V56 Compatibility)

### ISSUE THREAD

**Issue by DaXcess** [DaXcess/LCVR#242]
V56 has come out, and it adds several things that the VR mod currently does not like very much. Here's a list of things to do for V56 to become compatible with VR:

- [x] Add controller rebinding (Introduced in scrapped version 1.2.6)
- [x] Fix freeroam spectating bug on new entity
- [x] Fix freeroam spectating not working when quitting the game during spectating and joining a new session
- [x] ~~Rewrite~~ Fix player locomotion system for car
- [x] Add car interactions (buttons, ignition, stick shift, steering wheel)
- [x] Fix 6DOF while parent to car
- [x] Fix bug where FingerCurler.ForceFist doesn't work consistently
- [x] Fix head not syncing anymore
- [x] Fix VR player animations for other players in car
- [x] Add network sync for car (steering wheel and gear stick)
- [x] Add non-vr "sync" to steering wheel (will desync, but at least play animations)
- [x] Fix VR player animations not working when observed by a vanilla player
- [x] Fix reset height in car to account for car rotation
- [x] Fix dead VR players having collision with car (can still stand on car, car will drive through dead players)
- [x] Add special interaction for magnet lever (just like Artiface levers)
- [x] Fix reset height rotation being wrong if the animation point is deeply nested
- [x] Add some leftover UI elements back into VR
- [x] :egg: 
- [x] Item pickup breaking when having held a QE interactable item
- [x] More recenter fixes
- [x] Better sync for other VR players in ~~car~~ animations since the XR Origin position seems to be way off
- [x] Add push to talk UI into VR
- [x] Weed killer directional
- [x] Fix car ownership issues causing desync
- [x] Sync spectator physics parent to reduce jittering **[MAYBE FIXED]**
- [x] Add turning keybind to the keybind settings panel
- [x] ~~Small item placement improvement~~ **Scrapped because this isn't possible due to inconsistent and unpredictable rotations**
- [x] Disable alpha cutoff on the clay surgeon material if player is dead
- [x] Remove Discord onboarding warning about V56 incompatibility

**Cleanup**:
- [x] Go through all the TODOs

**External requirements**:
- [x] Lethal Company V56 full release

*This list is subject to change*

**Comment by pulpocaminante** [comment]
Just wanted to say I've been watching the list of to-dos go down every day and I'm really impressed by the speed with which you've updated this. You're the MVP :-)

**Comment by BigAtomikku** [comment]
> Just wanted to say I've been watching the list of to-dos go down every day and I'm really impressed by the speed with which you've updated this. You're the MVP :-)

agreed, although I do wish they would've released a compatibility fix for V56 sooner even if it didn't include every task finished. My friends and I have lethal company VR game nights a couple times every week and had to find a different game for the time being. I did spend a couple of hours learning how to compile my own though and we got it working last Wednesday so, at least I've figured out how to do my own hotfix now.

**Comment by DaXcess** [comment]
> agreed, although I do wish they would've released a compatibility fix for V56 sooner even if it didn't include every task finished. My friends and I have lethal company VR game nights a couple times every week and had to find a different game for the time being. I did spend a couple of hours learning how to compile my own though and we got it working last Wednesday so, at least I've figured out how to do my own hotfix now.

I disagree on this. I always go for a full finished product instead of making something "half assed" just so it launches. Combine this with the fact that V56 has broken some stuff in LCVR (that have nothing to do with the new features), and you see why I didn't opt for just adding the hash.

Plus, you can just add '--lcvr-skip-checksum' which bypasses integrity checks.

**Comment by BigAtomikku** [comment]
> > agreed, although I do wish they would've released a compatibility fix for V56 sooner even if it didn't include every task finished. My friends and I have lethal company VR game nights a couple times every week and had to find a different game for the time being. I did spend a couple of hours learning how to compile my own though and we got it working last Wednesday so, at least I've figured out how to do my own hotfix now.
> 
> I disagree with this. I always go for a full finished product instead of making something "half assed" just so the mod launches. Combine this with the fact that V56 has broken some stuff in LCVR (that have nothing to do with the new features), and you see why I didn't opt for just adding the hash.
> 
> Plus, you can just add '--lcvr-skip-checksum' to the launch options, which bypasses integrity checks (but stuff might be broken).
> 
> At least it shouldn't matter now since 1.3.0 debug builds are now available as artifacts.

That's understandable as you are author of the mod and want to uphold quality. I am looking at it from a birds eye view with no knowledge or attachment to perfect quality. Upon my testing of compiling pre release last Wednesday, everything worked as I needed it to play the game in VR so I was happy, anything uncompleted in the checklist at the time was too in depth for me to notice. I did not see it as "half assed" and just happy I could play again. I'm not just saying to add the hash either and push it. Ideally for me, the stuff that breaks LCVR should be priority and then updates can always keep rolling out adding fixes and quality of life stuff every couple days as you work on it. Whenever I open my thunderstore I have a bunch of mods needing updates anyway so it's nothing unusual. It's just a different point of view on rolling out updates. As a dev, I get it. As a consumer, I just wanna get back into the gameplay asap.

**Comment by DaXcess** [comment]
> That's understandable as you are author of the mod and want to uphold quality. I am looking at it from a birds eye view with no knowledge or attachment to perfect quality. Upon my testing of compiling pre release last Wednesday, everything worked as I needed it to play the game in VR so I was happy, anything uncompleted in the checklist at the time was too in depth for me to notice. I did not see it as "half assed" and just happy I could play again. I'm not just saying to add the hash either and push it. Ideally for me, the stuff that breaks LCVR should be priority and then updates can always keep rolling out adding fixes and quality of life stuff every couple days as you work on it. Whenever I open my thunderstore I have a bunch of mods needing updates anyway so it's nothing unusual. It's just a different point of view on rolling out updates. As a dev, I get it. As a consumer, I just wanna get back into the gameplay asap.

Fair point. The "half assed" part was more so directed towards me (as an author). There's also some technical limitations that would have come with a more simple approach (broken patches for example), and people going back to v50 because of *other* mods that weren't compatible with V55 yet.
It's kind of the reason why I added the `--lcvr-skip-checksum` flag to play older LCVR versions on V55, though it's undocumented because, well, there's no telling as to what might break (partially or completely).

And yeah the part of *'focus on the breaking bugs, then the features'* is purely preference. I chose to go for 100% completion, others (devs) might choose to first bump it up to be compatible with the new version, and then add the new features.

**Comment by olliebon** [comment]
> > Just wanted to say I've been watching the list of to-dos go down every day and I'm really impressed by the speed with which you've updated this. You're the MVP :-)
> 
> agreed, although I do wish they would've released a compatibility fix for V56 sooner even if it didn't include every task finished. My friends and I have lethal company VR game nights a couple times every week and had to find a different game for the time being. I did spend a couple of hours learning how to compile my own though and we got it working last Wednesday so, at least I've figured out how to do my own hotfix now.

SEND????

**Comment by DaXcess** [comment]
https://github.com/DaXcess/LCVR/actions

**Comment by DaXcess** [comment]
woops didn't mean to close

**Comment by BigAtomikku** [comment]
> SEND????

If you get visual studio and follow the instructions DaXcess has laid out, making sure to include nuget package source, it's fairly easy. I thank them for making those instructions, made it easy to get going. Only thing I had to figure out was the lethalvrcompany file, in the code it's hard coded to somewhere on his F drive and I just had to rename the location. Not sure how this works in releases. 

The mod seems close to being done so I'm sure it won't be too much longer. With devs permission, if it's gonna be a bit longer, I wouldn't mind sending here with some instructions. As I said though, isn't too hard if you have a couple hours to fiddle with it.

**Comment by AlwaysBeApexing** [comment]
Hey keep up the great work

**Comment by pulpocaminante** [comment]
Honestly if you don't like the release schedule, go write your own VR mod. It's incredibly rude to complain about, a massive amount of work goes into making something like this for the community.

**Comment by EchoLWS999** [comment]
you are amazing.

**Comment by AlwaysBeApexing** [comment]
I honestly feel bad considering almost as soon as you release it another version will come out lol

**Comment by DaXcess** [comment]
I'm not really that afraid of V60, as AFAIK it doesn't add anything revolutionary like an entire car. So VR might not need a lot of tweaking for it to work.

**Comment by BigAtomikku** [comment]
Hopefully not. I will say, though, the cruiser is working anazing in VR. Great job with it @DaXcess

**Comment by YourLocalIdiot123** [comment]
Hello.

**Comment by MrModdd** [comment]
One more to fix! cant wait to play it :)

**Comment by ThatOneSaint** [comment]
I tried to import this mod into the code to get it to work but it kept giving me the same incompatibility error, super ready for this to drop! Keep up the good work!

**Comment by DaXcess** [comment]
1.3.0 has been released
