### ISSUE TITLE
LCVR with keyboard and mouse ?

### ISSUE THREAD

**Issue by Svefn23** [DaXcess/LCVR#245]
Hi,

Since I only do flight sim stuff with my VR headset, I don't have controllers and I don't need them, and I wonder if I can use LCVR with keyboard and mouse, and if it's possible, how do I configure it ?

Thanks in advance,
Have a good day.

**Comment by DaXcess** [comment]
LCVR does not support M+K, and there are no plans to support it in this mod in the future
