### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by MasterJuli** [DaXcess/LCVR#249]
![image](https://github.com/user-attachments/assets/ec3486c4-ad59-4046-82c9-27a3d7de5b60)

As you can see in the picture, it doesn't really want to start. With the mod disabled, everything works perfectly fine and I only have those two mods enabled:

![image](https://github.com/user-attachments/assets/9abf9444-f8a4-4615-917c-dab151276a95)

**Comment by DaXcess** [comment]
v1.2.5 doesn't support V56, you need to downgrade Lethal Company to play with the mod

**Comment by MasterJuli** [comment]
Thanks
