### ISSUE TITLE
Black screen

### ISSUE THREAD

**Issue by Mills888dev** [DaXcess/LCVR#25]
I get an error every time I try to play and the game just shows a black screen in my headset and on pc (I'm using a valve index)
Log:
[LogOutput.log](https://github.com/DaXcess/LCVR/files/13800832/LogOutput.log)

**Comment by AyOhEe** [comment]
```log
[Debug  :      LCVR] Early loading MoreCompany.dll
[Debug  :      LCVR] Early loading Unity.Animation.Rigging.dll
[Debug  :      LCVR] Early loading Unity.InputSystem.dll
[Debug  :      LCVR] Early loading Unity.Netcode.Runtime.dll
[Debug  :      LCVR] Early loading Unity.RenderPipelines.Core.Runtime.dll
[Debug  :      LCVR] Early loading Unity.RenderPipelines.HighDefinition.Runtime.dll
[Debug  :      LCVR] Early loading Unity.TextMeshPro.dll
[Debug  :      LCVR] Early loading Unity.XR.CoreUtils.dll
[Debug  :      LCVR] Early loading Unity.XR.Interaction.Toolkit.dll
[Debug  :      LCVR] Early loading Unity.XR.Management.dll
[Debug  :      LCVR] Early loading Unity.XR.OpenXR.dll
[Debug  :      LCVR] Early loading UnityEngine.SpatialTracking.dll
[Debug  :      LCVR] Early loading UnityEngine.UI.dll
```

Looks like you have a lot more Dlls in RuntimeDeps than you need. Might be causing some issues?
I've been able to run without any issues, here are the Dlls I've been using:

- openxr_loader.dll
- UnityOpenXR.dll
- Unity.XR.CoreUtils.dll
- Unity.XR.Interaction.Toolkit.dll
- Unity.XR.Management.dll
- Unity.XR.OpenXR.dll
- UnityEngine.SpatialTracking.dll

Try removing the extra Dlls and see if that fixes anything.

**Comment by walterman105** [comment]
Where did you get `Unity.XR.CoreUtils.dll` and `UnityEngine.SpatialTracking.dll`? Those do not seem to be including with the project.

**Comment by AyOhEe** [comment]
Following the advice under #19. Perhaps they are unnecessary, but I don't know. Feel free to try running without them

**Comment by walterman105** [comment]
Well it made the errors go away along with the flashing purple box. But I am still unable to navigate the UI or seem my controllers. I put more info in a new issue #27

**Comment by ethanbradshaw** [comment]
Hey, have you tried following these instructions yet? I know at least for me using the provided DLL's in the repo didn't seem to work for me, but once I grabbed fresh ones from a unity project everything worked perfect for me, also what GPU are you on? AMD GPU's seem to be having issues from what I've seen from various users
![image](https://github.com/DaXcess/LCVR/assets/65248093/f2387b01-b1c6-4e6c-aaa9-0a1b381f97d6)

**Comment by walterman105** [comment]
Yes I have followed that and it still doesn't work. I am using an AMD GPU. I might test on my old Nvidia GPU and see if anything changes.

**Comment by Mills888dev** [comment]
removing excess DLLs worked.
