### ISSUE TITLE
LCVR 1.3 Dependency Error

### ISSUE THREAD

**Issue by AnaxMorden** [DaXcess/LCVR#253]
## Description
Hey,
Really nice mod you wrote.
But to get to a point:
I currently tried to load the mod and compiled it said like in the README
My Problem here: I get a dependency error!
![problem](https://github.com/user-attachments/assets/c1395580-deee-4cce-9ff9-008f250a8139)

## Installation Steps
(Im using an Linux setup without VR just to test the beta)
- Installed `r2modman`
- Installed the stable release VR mod from there
- compiled everything from dev Branch
- Overwrote the old .dll from the Stable release
- Tried to run it

## Enviroment
OS: ArchLinux
Packages: Latest bleeding edge packages for compiling

**Comment by DaXcess** [comment]
So as it says, you need to also install the FixPluginTypesSerialization mod. If using a mod manager, the popular ones do not resolve dependencies automatically for some reason (TMM/R2). The only one that resolves dependencies on Local Mods is Gale.
