### ISSUE TITLE
Game closes after 3 seconds 

### ISSUE THREAD

**Issue by BucketofWater1** [DaXcess/LCVR#255]
![Screenshot 2024-08-10 082631](https://github.com/user-attachments/assets/c67b8873-266d-443c-afac-c9f03a016c2d)

**Comment by BucketofWater1** [comment]
it closes and i tried fixing it like Daniel said but i dont know how to

**Comment by DaXcess** [comment]
Not an issue with LCVR in itself, as there are no error logs to be seen.
