### ISSUE TITLE
Menu truck does not play musical car horn sound effect

### ISSUE THREAD

**Issue by RidgeXR** [DaXcess/LCVR#257]
Menu truck does not play musical car horn sound effect help
![luig no](https://github.com/user-attachments/assets/4ecd2700-a902-4fa4-a0a2-837bb4cdfad7)

**Comment by DaXcess** [comment]
I'm deeply sorry and saddened by this revelation

**Comment by DaXcess** [comment]
No more car :(

**Comment by RidgeXR** [comment]
day ruined
