### ISSUE TITLE
Menu pointers do not work

### ISSUE THREAD

**Issue by Freddy3DS** [DaXcess/LCVR#260]
In the menu's the interaction lasers don't appear. I can enable and disable the one on your right hand for in-game interactions, just not for the menu's. There doesn't seem to be a toggle to turn it on or off, so I'm hoping someone has a solution.

**Comment by DaXcess** [comment]
CullFactory requires LethalPerformance to work in VR. It's either that or you need to entirely remove CullFactory.

**Comment by Freddy3DS** [comment]
Huge thanks fellas! Cull Factory was the issue.
