### ISSUE TITLE
Some feature ideas

### ISSUE THREAD

**Issue by TinyDerp** [DaXcess/LCVR#262]
I got some 3am inspiration last night and came up with these ideas to imploment into LCVR.

What if pointing and dancing in IRL (doing kinda similar movements not 1 to 1) would trigger the corresponding action ingame so non-vr players who dont have the mod installed could see it. This would also fix incompatibilities with other [niche](https://thunderstore.io/c/lethal-company/p/Kittenji/Football/) mods as well. Oc if this is something too hard to imploment like it was with the jetpack and item rotations I would at least like to have the option to bind those actions to button combinations not only to a single button like right now.
Speaking of rebinding it would be awesome if rebinding would use the [LethalCompany InputUtils](https://thunderstore.io/c/lethal-company/p/Rune580/LethalCompany_InputUtils/) mod because, well, the vanilla one sucks ass. 
Also what if the config for VR setting would be in [LethalConfig](https://thunderstore.io/c/lethal-company/p/AinaVT/LethalConfig/) instead of there being an extra button that tbh look kinda bad if you have MoreCompany installed as its not aligned and not the same size.

**Comment by DaXcess** [comment]
Motion detection is not something I want to get into as that is just way to complex for such a simple task.

InputUtils doesn't support VR, so I can't do anything with that one.

LethConfig integration has been planned for a while now, but no efforts have been made for it yet.

**Comment by TinyDerp** [comment]
What about button combinations for emotes?

**Comment by DaXcess** [comment]
Modifier bindings must be defined beforehand (during InputActionAsset building), and cannot be created magically by rebinding, unless you hack into Unity's inputsystem

**Comment by TinyDerp** [comment]
Okay then one last question then. How to I unbind?

**Comment by DaXcess** [comment]
By resetting all bindings, the rebinding system in 1.3.0 is still experimental and has no individual unbinding as of yet

**Comment by TinyDerp** [comment]
Thanks 👍
