### ISSUE TITLE
Version 60 is out

### ISSUE THREAD

**Issue by Marsson90** [DaXcess/LCVR#264]
Hey there! How quick do you think that your mod will be updated to work with the new update?

**Comment by AmeliaGL0w0** [comment]
v60 came out a few minutes ago, daniel i assume is still sleeping. no eta, give him time

**Comment by AmeliaGL0w0** [comment]
and i dont want to spoil anything, but i can predict that it may take almost as long as v56 lcvr

**Comment by Marsson90** [comment]
> v60 came out a few minutes ago, daniel i assume is still sleeping. no eta, give him time

Yeah of course :) I'm just curious since I remember him mentioning that the next update would probably be quicker somewhere.

**Comment by AmeliaGL0w0** [comment]
if you want to join beta playtests of v60 lcvr in the future, you can join the official lcvr discord https://discord.gg/Wub7EVUw

**Comment by DaXcess** [comment]
Update is here
