### ISSUE TITLE
Cannot navigate UI on Quest 2, no errors in console.

### ISSUE THREAD

**Issue by walterman105** [DaXcess/LCVR#27]
I was able to get the mod to fully load without any noticeable errors using the instructions listed here [#19](https://github.com/DaXcess/LCVR/issues/19).

The game seems to load fine but I don't see the controllers appear on screen and I am unable to navigate the UI. I am using an oculus quest 2. I've tried it over Steam Link, Air Link and wired to my pc.

Here is my log:
[LogOutput.log](https://github.com/DaXcess/LCVR/files/13802445/LogOutput.log)

**Comment by ethanbradshaw** [comment]
Are you using the unity DLL's provided by the repo or from a fresh unity project?

**Comment by walterman105** [comment]
From a fresh unity project. 
My `RuntimeDeps` folder has the follow:
- openxr_loader.dll
- Unity.XR.CoreUtils.dll
- Unity.XR.Interaction.Toolkit.dll
- Unity.XR.Management.dll
- Unity.XR.OpenXR.dll
- UnityEngine.SpatialTracking.dll
- UnityOpenXR.dll

with `UnityOpenXR.dll` and `openxr_loader.dll` being from the repo.

**Comment by ethanbradshaw** [comment]
Can I try sending you my profile for R2Modman? odd that its not working as it sounds like it should

**Comment by walterman105** [comment]
Sure I’ll try it out and see if it makes any difference.

**Comment by walterman105** [comment]
**Found the issue**: The issue appears to be related to the fact that I am using an AMD GPU and doesn't really have anything to do with using an Oculus Quest. Now I'll just wait until they add better support for AMD GPUs.
