### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by StarleetOsu** [DaXcess/LCVR#270]
![Скриншот 16-09-2024 022015](https://github.com/user-attachments/assets/241ffb4b-4f83-437a-b265-3abca4a73c19)
HELP

**Comment by DaXcess** [comment]
Update your game

**Comment by StarleetOsu** [comment]
> Update your game

I'm playing on the latest version of the game with the latest version of the mod

**Comment by StarleetOsu** [comment]
https://github.com/user-attachments/assets/3defe897-a47a-4527-873f-8c2c8bfa86e8

**Comment by DaXcess** [comment]
LCVR only works on the official Steam version of LC
