### ISSUE TITLE
Controllers are positioned high above head

### ISSUE THREAD

**Issue by IanF1090** [DaXcess/LCVR#28]
Mod works with all things installed correctly. However, my arms and hands are about 5 or 6 feet over my head. picking up objects still worked. Using quest 2.

Log: 
[LogOutput.log](https://github.com/DaXcess/LCVR/files/13802739/LogOutput.log)

**Comment by ethanbradshaw** [comment]
Hey, Do you have MoreEmotes enabled? It looks like MoreEmotes is not compatible at this time (or possibly ever) since it utilizes a different model than the default one. I was also getting this issue and disabling MoreEmotes fixed it

**Comment by IanF1090** [comment]
I just tested it, it works. I don't know why i didn't see if it worked without other mods first. Thanks!

**Comment by ethanbradshaw** [comment]
Hey! If you need an emote mod for desktop players playing alongside it looks like TooManyEmotes is compatible!

**Comment by IanF1090** [comment]
I'll check it out. Thanks again!
