### ISSUE TITLE
Motion tracking not working with controllers

### ISSUE THREAD

**Issue by CuteNatalie** [DaXcess/LCVR#30]
![image](https://github.com/DaXcess/LCVR/assets/55960119/49d54ba7-eea5-412f-a427-4a6b476089bb)
The arms of my character are kinda just stuck up in the air

**Comment by DaXcess** [comment]
Disable all other mods and try again, there is a zero guarantee policy on the compatibility with other mods at this moment

**Comment by ethanbradshaw** [comment]
The issue here is any Emote related mods, I assume you have MoreEmotes, disable that and you should be fixed
