### ISSUE TITLE
Interaction loss when picking stuff up

### ISSUE THREAD

**Issue by Phil25** [DaXcess/LCVR#32]
I'm using the binaries compiled by Zeleny on Discord posted [here](https://discord.com/channels/747967102895390741/1173840916788809779/1192958396505276447), I believe it's up to date with the current main at time of writing.

I was on the Index and around 2h into the session my ability to interact with anything was completely gone, the GUI didn't appear at all. However, my controllers worked and I could move around without any issues. I didn't experience any problems up until this point.

Dying didn't help and I made sure the game is focused on my monitor. The only thing that fixed it is going to main menu and creating a game again.

Excerpt from the logs that seems important:
```
[Info   : Unity Log] grabInvalidated: False
[Info   : Unity Log] grabInvalidated: False
[Info   : Unity Log] grabInvalidated: False
[Info   : Unity Log] Despawning props and enemies #2
[Info   : Unity Log] Despawning props and enemies #3
[Info   : Unity Log] Enemies on map: 13
[Info   : Unity Log] Despawning enemy: Centipede(Clone)
[Info   : Unity Log] Despawning enemy: HoarderBug(Clone)
[Info   : Unity Log] Despawning enemy: Flowerman(Clone)
[Info   : Unity Log] Despawning enemy: DoublewingedBird(Clone)
[Info   : Unity Log] Despawning enemy: DoublewingedBird(Clone)
[Info   : Unity Log] Despawning enemy: DocileLocustBees(Clone)
[Info   : Unity Log] Despawning enemy: DoublewingedBird(Clone)
[Info   : Unity Log] Despawning enemy: DocileLocustBees(Clone)
[Info   : Unity Log] Despawning enemy: RedLocustBees(Clone)
[Info   : Unity Log] Despawning enemy: DocileLocustBees(Clone)
[Info   : Unity Log] Despawning enemy: DocileLocustBees(Clone)
[Info   : Unity Log] Despawning enemy: RedLocustBees(Clone)
[Info   : Unity Log] Despawning enemy: RedLocustBees(Clone)
[Info   : Unity Log] grabInvalidated: False
[Info   : Unity Log] grabInvalidated: False
(same message spammed)
[Info   : Unity Log] grabInvalidated: False
[Info   : Unity Log] grabInvalidated: False
[Warning: Unity Log] [Netcode] NetworkObject #746 moved to the root because its parent NetworkObject #747 is destroyed
[Warning: Unity Log] [Netcode] NetworkObject #743 moved to the root because its parent NetworkObject #747 is destroyed
[Info   : Unity Log] grabInvalidated: False
[Info   : Unity Log] grabInvalidated: False
(same message spammed hundreds of times)
[Info   : Unity Log] grabInvalidated: False
[Info   : Unity Log] grabInvalidated: False
[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
GameNetcodeStuff.PlayerControllerB+<GrabObject>d__350.MoveNext () (at <44743d9474784365a095189c76175301>:0)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <e27997765c1848b09d8073e5d642717a>:0)

[Info   : Unity Log] Level up timer: 0
[Info   : Unity Log] Reviving players A
[Info   : Unity Log] Reviving players B
[Info   : Unity Log] Reviving players C
```

I think these logs roughly happened when I tried to pick up a beehive and died at the same time, resetting the round:

https://github.com/DaXcess/LCVR/assets/16500675/4466c4c6-8292-4fd4-a1a7-c1b09cd95922

After respawning, I couldn't interact with anything.

Attaching full logs below:
[LogOutput - Iteraction broke.log](https://github.com/DaXcess/LCVR/files/13847465/LogOutput.-.Iteraction.broke.log)

This also could be a base game bug and unrelated to LCVR.

**Comment by bavninja** [comment]
Quite sure this is a main game bug, I've experienced this most when in someone elses server (desync). Altough it could also be one of the mods I used it those flat screen instances. At least you where able to enjoy 2 hours of gameplay before this, only fix I know of when I experienced this is rejoining your save... 😞

**Comment by Phil25** [comment]
Yeah, looking the issue up seems to indicate it's a base game bug. I wish it was open source and on GitHub as well lol.

Closing as unrelated.

**Comment by DaXcess** [comment]
While this might be a base game bug, the code that handles the item pickup in VR is not using the base game code, but a cloned version of it. I might add some debugging after release that logs the reason for why an item could not be picked up/interacted with.

I'll reopen this issue for now because a game update might not fix the issue in the VR version.

**Comment by DaXcess** [comment]
Played with a bunch of bigger lobbies, never seen this issue, so I'll go ahead and close it again. It might have indeed been a V45 bug after all.
