### ISSUE TITLE
Not launchable in VR

### ISSUE THREAD

**Issue by DevilsCharm** [DaXcess/LCVR#34]
Hey guys, just tried a shitload to make it run.
After getting the missing unity deps (didn't see a release where I can download it)
The game now boots in VR, but I get the same error every second and I don't see any in game Stuff (Neither in VR nor Desktop, but I can hear sounds)

STACK:
`[Message:   BepInEx] BepInEx 5.4.22.0 - Lethal Company (06.01.2024 13:52:47)
[Info   :   BepInEx] Running under Unity v2022.3.9.15351836
[Info   :   BepInEx] CLR runtime version: 4.0.30319.42000
[Info   :   BepInEx] Supports SRE: True
[Info   :   BepInEx] System platform: Bits64, Windows
[Message:   BepInEx] Preloader started
[Info   :   BepInEx] Loaded 1 patcher method from [BepInEx.Preloader 5.4.22.0]
[Info   :   BepInEx] 1 patcher plugin loaded
[Info   :   BepInEx] Patching [UnityEngine.CoreModule] with [BepInEx.Chainloader]
[Message:   BepInEx] Preloader finished
[Message:   BepInEx] Chainloader ready
[Message:   BepInEx] Chainloader started
[Info   :   BepInEx] 4 plugins to load
[Warning:   BepInEx] Skipping [LCVR 0.0.1] because a newer version exists (LCVR 0.0.1)
[Info   :   BepInEx] Loading [MoreCompany 1.7.2]
[Info   :MoreCompany] Loading MoreCompany...
[Info   :MoreCompany] Checking: C:\Program Files (x86)\Steam\steamapps\common\Lethal Company\BepInEx\plugins/MoreCompanyCosmetics
[Info   :MoreCompany] Read settings and cosmetics
[Info   :MoreCompany] Loaded cosmetic: builtin.3dglasses from bundle
[Info   :MoreCompany] Loaded cosmetic: builtin.bunnyears from bundle
[Info   :MoreCompany] Loaded cosmetic: builtin.denimhat from bundle
[Info   :MoreCompany] Loaded cosmetic: builtin.fancyglasses from bundle
[Info   :MoreCompany] Loaded cosmetic: builtin.partyglasses from bundle
[Info   :MoreCompany] Loaded cosmetic: builtin.gunholster from bundle
[Info   :MoreCompany] Loaded cosmetic: builtin.hardhat from bundle
[Info   :MoreCompany] Loaded cosmetic: builtin.jesterhat from bundle
[Info   :MoreCompany] Loaded cosmetic: builtin.kittyears from bundle
[Info   :MoreCompany] Loaded cosmetic: builtin.mimemask from bundle
[Info   :MoreCompany] Loaded cosmetic: builtin.fancypants from bundle
[Info   :MoreCompany] Loaded cosmetic: builtin.outoforder from bundle
[Info   :MoreCompany] Loaded cosmetic: builtin.partyhat from bundle
[Info   :MoreCompany] Loaded cosmetic: builtin.plaguemask from bundle
[Info   :MoreCompany] Loaded cosmetic: builtin.propellerhat from bundle
[Info   :MoreCompany] Loaded cosmetic: builtin.eyeballs from bundle
[Info   :MoreCompany] Loaded cosmetic: builtin.rudolph from bundle
[Info   :MoreCompany] Loaded cosmetic: builtin.santahat from bundle
[Info   :MoreCompany] Loaded cosmetic: builtin.slimething from bundle
[Info   :MoreCompany] Loaded cosmetic: builtin.tophat from bundle
[Info   :MoreCompany] Loaded cosmetic: builtin.watch from bundle
[Info   :MoreCompany] Loading USER COSMETICS...
[Info   :MoreCompany] Loaded MoreCompany FULLY
[Info   :   BepInEx] Loading [LCVR 0.0.1]
[Info   :      LCVR] Found compatible mod MoreCompany
[Info   :      LCVR] Plugin LCVR is starting...
[Info   :      LCVR] Loading VR...
[Info   : Unity Log] XRGeneral Settings awakening...
Error [GENERAL | xrCreateInstance | OpenXR-Loader] : LoaderInstance::CreateInstance chained CreateInstance call failed
Error [GENERAL | xrCreateInstance | OpenXR-Loader] : xrCreateInstance failed
[Info   :      LCVR] Initialized OpenXR Runtime
[Error  :      LCVR] Failed to start in VR Mode! Only Non-VR features are available!
[Info   :   BepInEx] Loading [Lethal Company GameMaster 1.0.0.0]
[Info   :GameMaster] Loaded GameMaster. Patching.
[Info   :Lethal Company GameMaster] GUILoader loaded.
[Message:   BepInEx] Chainloader startup complete
[Error  : Unity Log] ArgumentException: An item with the same key has already been added. Key: UnityEngine.Rendering.ProbeVolumesOptions
Stack trace:
System.Collections.Generic.Dictionary`2[TKey,TValue].TryInsert (TKey key, TValue value, System.Collections.Generic.InsertionBehavior behavior) (at <787acc3c9a4c471ba7d971300105af24>:0)
System.Collections.Generic.Dictionary`2[TKey,TValue].Add (TKey key, TValue value) (at <787acc3c9a4c471ba7d971300105af24>:0)
UnityEngine.Rendering.VolumeStack.Reload (System.Collections.Generic.List`1[T] componentDefaultStates) (at <3e4d5d98dfc34520bf7c624af5a98275>:0)
UnityEngine.Rendering.VolumeManager.CreateStack () (at <3e4d5d98dfc34520bf7c624af5a98275>:0)
UnityEngine.Rendering.VolumeManager..ctor () (at <3e4d5d98dfc34520bf7c624af5a98275>:0)
UnityEngine.Rendering.VolumeManager+<>c.<.cctor>b__46_0 () (at <3e4d5d98dfc34520bf7c624af5a98275>:0)
System.Lazy`1[T].ViaFactory (System.Threading.LazyThreadSafetyMode mode) (at <787acc3c9a4c471ba7d971300105af24>:0)
System.Lazy`1[T].ExecutionAndPublication (System.LazyHelper executionAndPublication, System.Boolean useDefaultConstructor) (at <787acc3c9a4c471ba7d971300105af24>:0)
System.Lazy`1[T].CreateValue () (at <787acc3c9a4c471ba7d971300105af24>:0)
System.Lazy`1[T].get_Value () (at <787acc3c9a4c471ba7d971300105af24>:0)
UnityEngine.Rendering.VolumeManager.get_instance () (at <3e4d5d98dfc34520bf7c624af5a98275>:0)
UnityEngine.Rendering.Volume.OnEnable () (at <3e4d5d98dfc34520bf7c624af5a98275>:0)

[Info   : Unity Log] Changing gamma
[Info   : Unity Log] override float value: 0
[Info   : Unity Log] Overriding float
[Info   : Unity Log] Gamma changed
[Info   : Unity Log] Set gamma to new value: 0; (0.00, 0.00, 0.00, 0.00) (True)
[Error  : Unity Log] ArgumentException: An item with the same key has already been added. Key: UnityEngine.Rendering.ProbeVolumesOptions
Stack trace:
System.Collections.Generic.Dictionary`2[TKey,TValue].TryInsert (TKey key, TValue value, System.Collections.Generic.InsertionBehavior behavior) (at <787acc3c9a4c471ba7d971300105af24>:0)
System.Collections.Generic.Dictionary`2[TKey,TValue].Add (TKey key, TValue value) (at <787acc3c9a4c471ba7d971300105af24>:0)
UnityEngine.Rendering.VolumeStack.Reload (System.Collections.Generic.List`1[T] componentDefaultStates) (at <3e4d5d98dfc34520bf7c624af5a98275>:0)
UnityEngine.Rendering.VolumeManager.CreateStack () (at <3e4d5d98dfc34520bf7c624af5a98275>:0)
UnityEngine.Rendering.VolumeManager..ctor () (at <3e4d5d98dfc34520bf7c624af5a98275>:0)
UnityEngine.Rendering.VolumeManager+<>c.<.cctor>b__46_0 () (at <3e4d5d98dfc34520bf7c624af5a98275>:0)
System.Lazy`1[T].ViaFactory (System.Threading.LazyThreadSafetyMode mode) (at <787acc3c9a4c471ba7d971300105af24>:0)
--- End of stack trace from previous location where exception was thrown ---
System.LazyHelper.ThrowException () (at <787acc3c9a4c471ba7d971300105af24>:0)
System.Lazy`1[T].CreateValue () (at <787acc3c9a4c471ba7d971300105af24>:0)
System.Lazy`1[T].get_Value () (at <787acc3c9a4c471ba7d971300105af24>:0)
UnityEngine.Rendering.VolumeManager.get_instance () (at <3e4d5d98dfc34520bf7c624af5a98275>:0)
UnityEngine.Rendering.Volume.OnEnable () (at <3e4d5d98dfc34520bf7c624af5a98275>:0)

[Error  : Unity Log] ArgumentException: An item with the same key has already been added. Key: UnityEngine.Rendering.ProbeVolumesOptions
Stack trace:
System.Collections.Generic.Dictionary`2[TKey,TValue].TryInsert (TKey key, TValue value, System.Collections.Generic.InsertionBehavior behavior) (at <787acc3c9a4c471ba7d971300105af24>:0)
System.Collections.Generic.Dictionary`2[TKey,TValue].Add (TKey key, TValue value) (at <787acc3c9a4c471ba7d971300105af24>:0)
UnityEngine.Rendering.VolumeStack.Reload (System.Collections.Generic.List`1[T] componentDefaultStates) (at <3e4d5d98dfc34520bf7c624af5a98275>:0)
UnityEngine.Rendering.VolumeManager.CreateStack () (at <3e4d5d98dfc34520bf7c624af5a98275>:0)
UnityEngine.Rendering.VolumeManager..ctor () (at <3e4d5d98dfc34520bf7c624af5a98275>:0)
UnityEngine.Rendering.VolumeManager+<>c.<.cctor>b__46_0 () (at <3e4d5d98dfc34520bf7c624af5a98275>:0)
System.Lazy`1[T].ViaFactory (System.Threading.LazyThreadSafetyMode mode) (at <787acc3c9a4c471ba7d971300105af24>:0)
--- End of stack trace from previous location where exception was thrown ---
System.LazyHelper.ThrowException () (at <787acc3c9a4c471ba7d971300105af24>:0)
System.Lazy`1[T].CreateValue () (at <787acc3c9a4c471ba7d971300105af24>:0)
System.Lazy`1[T].get_Value () (at <787acc3c9a4c471ba7d971300105af24>:0)
UnityEngine.Rendering.VolumeManager.get_instance () (at <3e4d5d98dfc34520bf7c624af5a98275>:0)
UnityEngine.Rendering.HighDefinition.SkyManager.Build (UnityEngine.Rendering.HighDefinition.HDRenderPipelineAsset hdAsset, UnityEngine.Rendering.HighDefinition.HDRenderPipelineRuntimeResources defaultResources, UnityEngine.Rendering.HighDefinition.IBLFilterBSDF[] iblFilterBSDFArray) (at <6214bbc46efe4329a4e9806065941bb4>:0)
UnityEngine.Rendering.HighDefinition.HDRenderPipeline..ctor (UnityEngine.Rendering.HighDefinition.HDRenderPipelineAsset asset) (at <6214bbc46efe4329a4e9806065941bb4>:0)
UnityEngine.Rendering.HighDefinition.HDRenderPipelineAsset.CreatePipeline () (at <6214bbc46efe4329a4e9806065941bb4>:0)
UnityEngine.Rendering.RenderPipelineAsset.InternalCreatePipeline () (at <e27997765c1848b09d8073e5d642717a>:0)
UnityEngine.Rendering.RenderPipelineManager:DoRenderLoop_Internal(RenderPipelineAsset, IntPtr, Object)

[Error  : Unity Log] Exception: Blitter is already initialized. Please only initialize the blitter once or you will leak engine resources. If you need to re-initialize the blitter with different shaders destroy & recreate it.
Stack trace:
UnityEngine.Rendering.Blitter.Initialize (UnityEngine.Shader blitPS, UnityEngine.Shader blitColorAndDepthPS) (at <3e4d5d98dfc34520bf7c624af5a98275>:0)
UnityEngine.Rendering.HighDefinition.HDRenderPipeline..ctor (UnityEngine.Rendering.HighDefinition.HDRenderPipelineAsset asset) (at <6214bbc46efe4329a4e9806065941bb4>:0)
UnityEngine.Rendering.HighDefinition.HDRenderPipelineAsset.CreatePipeline () (at <6214bbc46efe4329a4e9806065941bb4>:0)
UnityEngine.Rendering.RenderPipelineAsset.InternalCreatePipeline () (at <e27997765c1848b09d8073e5d642717a>:0)
UnityEngine.Rendering.RenderPipelineManager:DoRenderLoop_Internal(RenderPipelineAsset, IntPtr, Object)`

**Comment by DevilsCharm** [comment]
`[Message:   BepInEx] BepInEx 5.4.22.0 - Lethal Company (06.01.2024 13:52:47)
[Info   :   BepInEx] Running under Unity v2022.3.9.15351836
[Info   :   BepInEx] CLR runtime version: 4.0.30319.42000
[Info   :   BepInEx] Supports SRE: True
[Info   :   BepInEx] System platform: Bits64, Windows
[Message:   BepInEx] Preloader started
[Info   :   BepInEx] Loaded 1 patcher method from [BepInEx.Preloader 5.4.22.0]
[Info   :   BepInEx] 1 patcher plugin loaded
[Info   :   BepInEx] Patching [UnityEngine.CoreModule] with [BepInEx.Chainloader]
[Message:   BepInEx] Preloader finished
[Message:   BepInEx] Chainloader ready
[Message:   BepInEx] Chainloader started
[Info   :   BepInEx] 4 plugins to load
[Warning:   BepInEx] Skipping [LCVR 0.0.1] because a newer version exists (LCVR 0.0.1)
[Info   :   BepInEx] Loading [MoreCompany 1.7.2]
[Info   :MoreCompany] Loading MoreCompany...
[Info   :MoreCompany] Checking: C:\Program Files (x86)\Steam\steamapps\common\Lethal Company\BepInEx\plugins/MoreCompanyCosmetics
[Info   :MoreCompany] Read settings and cosmetics
[Info   :MoreCompany] Loaded cosmetic: builtin.3dglasses from bundle
[Info   :MoreCompany] Loaded cosmetic: builtin.bunnyears from bundle
[Info   :MoreCompany] Loaded cosmetic: builtin.denimhat from bundle
[Info   :MoreCompany] Loaded cosmetic: builtin.fancyglasses from bundle
[Info   :MoreCompany] Loaded cosmetic: builtin.partyglasses from bundle
[Info   :MoreCompany] Loaded cosmetic: builtin.gunholster from bundle
[Info   :MoreCompany] Loaded cosmetic: builtin.hardhat from bundle
[Info   :MoreCompany] Loaded cosmetic: builtin.jesterhat from bundle
[Info   :MoreCompany] Loaded cosmetic: builtin.kittyears from bundle
[Info   :MoreCompany] Loaded cosmetic: builtin.mimemask from bundle
[Info   :MoreCompany] Loaded cosmetic: builtin.fancypants from bundle
[Info   :MoreCompany] Loaded cosmetic: builtin.outoforder from bundle
[Info   :MoreCompany] Loaded cosmetic: builtin.partyhat from bundle
[Info   :MoreCompany] Loaded cosmetic: builtin.plaguemask from bundle
[Info   :MoreCompany] Loaded cosmetic: builtin.propellerhat from bundle
[Info   :MoreCompany] Loaded cosmetic: builtin.eyeballs from bundle
[Info   :MoreCompany] Loaded cosmetic: builtin.rudolph from bundle
[Info   :MoreCompany] Loaded cosmetic: builtin.santahat from bundle
[Info   :MoreCompany] Loaded cosmetic: builtin.slimething from bundle
[Info   :MoreCompany] Loaded cosmetic: builtin.tophat from bundle
[Info   :MoreCompany] Loaded cosmetic: builtin.watch from bundle
[Info   :MoreCompany] Loading USER COSMETICS...
[Info   :MoreCompany] Loaded MoreCompany FULLY
[Info   :   BepInEx] Loading [LCVR 0.0.1]
[Info   :      LCVR] Found compatible mod MoreCompany
[Info   :      LCVR] Plugin LCVR is starting...
[Info   :      LCVR] Loading VR...
[Info   : Unity Log] XRGeneral Settings awakening...
Error [GENERAL | xrCreateInstance | OpenXR-Loader] : LoaderInstance::CreateInstance chained CreateInstance call failed
Error [GENERAL | xrCreateInstance | OpenXR-Loader] : xrCreateInstance failed
[Info   :      LCVR] Initialized OpenXR Runtime
[Error  :      LCVR] Failed to start in VR Mode! Only Non-VR features are available!
[Info   :   BepInEx] Loading [Lethal Company GameMaster 1.0.0.0]
[Info   :GameMaster] Loaded GameMaster. Patching.
[Info   :Lethal Company GameMaster] GUILoader loaded.
[Message:   BepInEx] Chainloader startup complete
[Error  : Unity Log] ArgumentException: An item with the same key has already been added. Key: UnityEngine.Rendering.ProbeVolumesOptions
Stack trace:
System.Collections.Generic.Dictionary`2[TKey,TValue].TryInsert (TKey key, TValue value, System.Collections.Generic.InsertionBehavior behavior) (at <787acc3c9a4c471ba7d971300105af24>:0)
System.Collections.Generic.Dictionary`2[TKey,TValue].Add (TKey key, TValue value) (at <787acc3c9a4c471ba7d971300105af24>:0)
UnityEngine.Rendering.VolumeStack.Reload (System.Collections.Generic.List`1[T] componentDefaultStates) (at <3e4d5d98dfc34520bf7c624af5a98275>:0)
UnityEngine.Rendering.VolumeManager.CreateStack () (at <3e4d5d98dfc34520bf7c624af5a98275>:0)
UnityEngine.Rendering.VolumeManager..ctor () (at <3e4d5d98dfc34520bf7c624af5a98275>:0)
UnityEngine.Rendering.VolumeManager+<>c.<.cctor>b__46_0 () (at <3e4d5d98dfc34520bf7c624af5a98275>:0)
System.Lazy`1[T].ViaFactory (System.Threading.LazyThreadSafetyMode mode) (at <787acc3c9a4c471ba7d971300105af24>:0)
System.Lazy`1[T].ExecutionAndPublication (System.LazyHelper executionAndPublication, System.Boolean useDefaultConstructor) (at <787acc3c9a4c471ba7d971300105af24>:0)
System.Lazy`1[T].CreateValue () (at <787acc3c9a4c471ba7d971300105af24>:0)
System.Lazy`1[T].get_Value () (at <787acc3c9a4c471ba7d971300105af24>:0)
UnityEngine.Rendering.VolumeManager.get_instance () (at <3e4d5d98dfc34520bf7c624af5a98275>:0)
UnityEngine.Rendering.Volume.OnEnable () (at <3e4d5d98dfc34520bf7c624af5a98275>:0)

[Info   : Unity Log] Changing gamma
[Info   : Unity Log] override float value: 0
[Info   : Unity Log] Overriding float
[Info   : Unity Log] Gamma changed
[Info   : Unity Log] Set gamma to new value: 0; (0.00, 0.00, 0.00, 0.00) (True)
[Error  : Unity Log] ArgumentException: An item with the same key has already been added. Key: UnityEngine.Rendering.ProbeVolumesOptions
Stack trace:
System.Collections.Generic.Dictionary`2[TKey,TValue].TryInsert (TKey key, TValue value, System.Collections.Generic.InsertionBehavior behavior) (at <787acc3c9a4c471ba7d971300105af24>:0)
System.Collections.Generic.Dictionary`2[TKey,TValue].Add (TKey key, TValue value) (at <787acc3c9a4c471ba7d971300105af24>:0)
UnityEngine.Rendering.VolumeStack.Reload (System.Collections.Generic.List`1[T] componentDefaultStates) (at <3e4d5d98dfc34520bf7c624af5a98275>:0)
UnityEngine.Rendering.VolumeManager.CreateStack () (at <3e4d5d98dfc34520bf7c624af5a98275>:0)
UnityEngine.Rendering.VolumeManager..ctor () (at <3e4d5d98dfc34520bf7c624af5a98275>:0)
UnityEngine.Rendering.VolumeManager+<>c.<.cctor>b__46_0 () (at <3e4d5d98dfc34520bf7c624af5a98275>:0)
System.Lazy`1[T].ViaFactory (System.Threading.LazyThreadSafetyMode mode) (at <787acc3c9a4c471ba7d971300105af24>:0)
--- End of stack trace from previous location where exception was thrown ---
System.LazyHelper.ThrowException () (at <787acc3c9a4c471ba7d971300105af24>:0)
System.Lazy`1[T].CreateValue () (at <787acc3c9a4c471ba7d971300105af24>:0)
System.Lazy`1[T].get_Value () (at <787acc3c9a4c471ba7d971300105af24>:0)
UnityEngine.Rendering.VolumeManager.get_instance () (at <3e4d5d98dfc34520bf7c624af5a98275>:0)
UnityEngine.Rendering.Volume.OnEnable () (at <3e4d5d98dfc34520bf7c624af5a98275>:0)

[Error  : Unity Log] ArgumentException: An item with the same key has already been added. Key: UnityEngine.Rendering.ProbeVolumesOptions
Stack trace:
System.Collections.Generic.Dictionary`2[TKey,TValue].TryInsert (TKey key, TValue value, System.Collections.Generic.InsertionBehavior behavior) (at <787acc3c9a4c471ba7d971300105af24>:0)
System.Collections.Generic.Dictionary`2[TKey,TValue].Add (TKey key, TValue value) (at <787acc3c9a4c471ba7d971300105af24>:0)
UnityEngine.Rendering.VolumeStack.Reload (System.Collections.Generic.List`1[T] componentDefaultStates) (at <3e4d5d98dfc34520bf7c624af5a98275>:0)
UnityEngine.Rendering.VolumeManager.CreateStack () (at <3e4d5d98dfc34520bf7c624af5a98275>:0)
UnityEngine.Rendering.VolumeManager..ctor () (at <3e4d5d98dfc34520bf7c624af5a98275>:0)
UnityEngine.Rendering.VolumeManager+<>c.<.cctor>b__46_0 () (at <3e4d5d98dfc34520bf7c624af5a98275>:0)
System.Lazy`1[T].ViaFactory (System.Threading.LazyThreadSafetyMode mode) (at <787acc3c9a4c471ba7d971300105af24>:0)
--- End of stack trace from previous location where exception was thrown ---
System.LazyHelper.ThrowException () (at <787acc3c9a4c471ba7d971300105af24>:0)
System.Lazy`1[T].CreateValue () (at <787acc3c9a4c471ba7d971300105af24>:0)
System.Lazy`1[T].get_Value () (at <787acc3c9a4c471ba7d971300105af24>:0)
UnityEngine.Rendering.VolumeManager.get_instance () (at <3e4d5d98dfc34520bf7c624af5a98275>:0)
UnityEngine.Rendering.HighDefinition.SkyManager.Build (UnityEngine.Rendering.HighDefinition.HDRenderPipelineAsset hdAsset, UnityEngine.Rendering.HighDefinition.HDRenderPipelineRuntimeResources defaultResources, UnityEngine.Rendering.HighDefinition.IBLFilterBSDF[] iblFilterBSDFArray) (at <6214bbc46efe4329a4e9806065941bb4>:0)
UnityEngine.Rendering.HighDefinition.HDRenderPipeline..ctor (UnityEngine.Rendering.HighDefinition.HDRenderPipelineAsset asset) (at <6214bbc46efe4329a4e9806065941bb4>:0)
UnityEngine.Rendering.HighDefinition.HDRenderPipelineAsset.CreatePipeline () (at <6214bbc46efe4329a4e9806065941bb4>:0)
UnityEngine.Rendering.RenderPipelineAsset.InternalCreatePipeline () (at <e27997765c1848b09d8073e5d642717a>:0)
UnityEngine.Rendering.RenderPipelineManager:DoRenderLoop_Internal(RenderPipelineAsset, IntPtr, Object)

[Error  : Unity Log] Exception: Blitter is already initialized. Please only initialize the blitter once or you will leak engine resources. If you need to re-initialize the blitter with different shaders destroy & recreate it.
Stack trace:
UnityEngine.Rendering.Blitter.Initialize (UnityEngine.Shader blitPS, UnityEngine.Shader blitColorAndDepthPS) (at <3e4d5d98dfc34520bf7c624af5a98275>:0)
UnityEngine.Rendering.HighDefinition.HDRenderPipeline..ctor (UnityEngine.Rendering.HighDefinition.HDRenderPipelineAsset asset) (at <6214bbc46efe4329a4e9806065941bb4>:0)
UnityEngine.Rendering.HighDefinition.HDRenderPipelineAsset.CreatePipeline () (at <6214bbc46efe4329a4e9806065941bb4>:0)
UnityEngine.Rendering.RenderPipelineAsset.InternalCreatePipeline () (at <e27997765c1848b09d8073e5d642717a>:0)
UnityEngine.Rendering.RenderPipelineManager:DoRenderLoop_Internal(RenderPipelineAsset, IntPtr, Object)`

**Comment by ToxesFoxes** [comment]
In RuntimeDeps you copied `Unity.RenderPipelines.HighDefinition.Runtime.dll` just remove it

**Comment by DevilsCharm** [comment]
Sorry for bothering you. Thanks for the help :D
Love your work guys keep it up
