### ISSUE TITLE
Issues with Helmet Cameras mod

### ISSUE THREAD

**Issue by RealMCoded** [DaXcess/LCVR#35]
Due to a recent update with this mod (as of writing, I tried it with commits [`3781be6`](https://github.com/DaXcess/LCVR/commit/3781be64c3d8d84a73409cf25d3812f0622b3268) and [`e567d4d`](https://github.com/DaXcess/LCVR/commit/e567d4df51ebf6779729586c81229374bccb4936)), it is no longer compatible with the [Helmet_Cameras](https://thunderstore.io/c/lethal-company/p/RickArg/Helmet_Cameras/) mod. However, a version of the mod that I compiled on 1/2/2024 9:06PM EST (pretty sure it uses commit [`b87472d`](https://github.com/DaXcess/LCVR/commit/b87472d50e32cf32ca9d665155802d035351f835))  does work fine with the Helmet_Cameras mod.

The following error is logged in the console constantly:
```
Stack trace:
LCVR.Player.IKRigFollowVRRig.LateUpdate () (at <00b3b0a3037f4038be1ec4dba9f7ff61>:IL_002F)

[Info   : Unity Log] [HELMET_CAMERAS] ERROR NULL REFERENCE
[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
```

Here is my LogOutput file as well: [LogOutput.log](https://github.com/DaXcess/LCVR/files/13851616/LogOutput.log)

**Comment by JTMCDev** [comment]
I'm gonna solve this one here for you. Use [Solo's Bodycams](https://thunderstore.io/c/lethal-company/p/CapyCat/Solos_Bodycams/) It works fine and doesnt have any issues. its configurable with resouluton in config.

**Comment by RealMCoded** [comment]
Oh, alright. I'll give it a shot.

**Comment by RealMCoded** [comment]
Tried it, I'm still getting this error in the console
```
[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
LCVR.Player.IKRigFollowVRRig.LateUpdate () (at <00b3b0a3037f4038be1ec4dba9f7ff61>:IL_002F)
```

I'm going to try disabling all my mods later, I'll provide an update later.

**Comment by RealMCoded** [comment]
Yeah it was on my end. i still had TooManyEmotes on by mistake.
