### ISSUE TITLE
Stuck on start

### ISSUE THREAD

**Issue by ToxesFoxes** [DaXcess/LCVR#36]
![image](https://github.com/DaXcess/LCVR/assets/29871037/69f3fefb-16c3-4f73-ad99-9ce2ca7a5885)

In BepInEx no errors or something, just game was freezed after 1.5 seconds after unity logo appeared.

**Comment by DaXcess** [comment]
This looks like a roadblock with trying to run a Unity XR game (or modded to be XR) running through proton. The actual VR part of this mod is incredibly small and everything is done via Unity's official XR modules. If those fail, it's out of my hands.

**Comment by Oslott1** [comment]
I had the exact same issue just the other day. What solved it for me was adding the 2 missing RuntimeDeps DLLs, (Unity.XR.CoreUtils.dll and UnityEngine.SpatialTracking.dll) and making sure that the DLLs that belong in the Lethal Company_Data/Managed were properly copied to the the game directory. I hope that helps fix your issue!

**Comment by ToxesFoxes** [comment]
I didn't understand anything, can you explain how to fix it in the end?
all libraries is already inside RuntimeDeps in LCVR mod
![image](https://github.com/DaXcess/LCVR/assets/29871037/fe85403d-cebe-44ba-b88a-81e15ab366c1)
![image](https://github.com/DaXcess/LCVR/assets/29871037/e70a0443-8461-4fe6-991e-b91e4ce90691)

**Comment by ToxesFoxes** [comment]
Found Debug lines in output
[Debug  :   BepInEx] Skipping loading Z:\[SomePath]\BepInEx\plugins\LCVR\RuntimeDeps\openxr_loader.dll because it's not a valid .NET assembly. Full error: Format of the executable (.exe) or library (.dll) is invalid.
[Debug  :   BepInEx] Skipping loading Z:\[SomePath]\BepInEx\plugins\LCVR\RuntimeDeps\UnityOpenXR.dll because it's not a valid .NET assembly. Full error: Format of the executable (.exe) or library (.dll) is invalid.

**Comment by DaXcess** [comment]
> Found Debug lines in output
> [Debug  :   BepInEx] Skipping loading Z:\[SomePath]\BepInEx\plugins\LCVR\RuntimeDeps\openxr_loader.dll because it's not a valid .NET assembly. Full error: Format of the executable (.exe) or library (.dll) is invalid.
> [Debug  :   BepInEx] Skipping loading Z:\[SomePath]\BepInEx\plugins\LCVR\RuntimeDeps\UnityOpenXR.dll because it's not a valid .NET assembly. Full error: Format of the executable (.exe) or library (.dll) is invalid.

BepInEx refuses to load those files since they're native Windows DLLs, not managed DLLs. This is normal behaviour.

**Comment by agmass** [comment]
> I had the exact same issue just the other day. What solved it for me was adding the 2 missing RuntimeDeps DLLs, (Unity.XR.CoreUtils.dll and UnityEngine.SpatialTracking.dll) and making sure that the DLLs that belong in the Lethal Company_Data/Managed were properly copied to the the game directory. I hope that helps fix your issue!

Hi, could you please elaborate a bit more? I'm not too familiar with proton and dlls so could you just tell me where to move what?

**Comment by agmass** [comment]
I've reached the same point as ToxesFoxes, I've managed to load the dlls into the launch paramaters but they aren't managed dlls so do not load

**Comment by terminal-case** [comment]
Just a heads-up, I created an issue for LCVR on proton that was then merged into the main Lethal Company ticket on the proton github issue tracker. Not sure whether this is useful, but just so any other Linux users have something to keep an eye on: https://github.com/ValveSoftware/Proton/issues/7320#issuecomment-1915254980

**Comment by DaXcess** [comment]
I've heard of some people having succeeded in launching LCVR on Linux using Wine/Proton.
Closing this issue then.

**Comment by terminal-case** [comment]
@DaXcess, sorry for bumping this again, but can you point us in the direction of these folks?

**Comment by DaXcess** [comment]
![image](https://github.com/DaXcess/LCVR/assets/46288749/61d10a9d-5142-499a-b776-8f634c9533be)

Someone in the LCVR Discord had gotten it to work on an AMD GPU using Wayland (and what looks to be ALVR).
Don't know what they did exactly and I no longer have a Linux setup on my PC so I can't test for myself.

**Comment by agmass** [comment]
This is an issue with NVIDIA gpus, so AMD would work fine. Just sad that the version of OpenXR the mod uses doesn't really like NVidia for whatever reason
