### ISSUE TITLE
SteamVR causes extreme shakiness

### ISSUE THREAD

**Issue by TylonBelmont** [DaXcess/LCVR#37]
Installed mod and it works fine using Oculus as the OpenXR runtime, but when trying to use SteamVR the screen is very shaky and doesn't seem to follow the headsets movements. I'm using a Quest 3 connected via link cable. Does it make a difference if it's launched via executable or from the steamvr menu? Would like to launch via steam to invite friends.

**Comment by JTMCDev** [comment]
SteamVR issue. not the mod

**Comment by DaXcess** [comment]
While not 100% sure, the SteamVR issue might be because SteamVR can't keep up with tracking/rendering while the game is running in VR (it is very resource intensive). One thing that is clear though is that this is not an issue with the mod, but with SteamVR.
