### ISSUE TITLE
Arms "flying" above the head

### ISSUE THREAD

**Issue by verba-dev** [DaXcess/LCVR#38]
Greetings! Found this mod as an interesting thing to try out, but I met an issue - I couldn't see my arms. And I thought that it was a normal thing to deal with, but when I looked up - boom! I saw my arms.
I thought of deleting a few mods that could interfere with the player's model bones, but that didn't work. I tried deleting every single mod except LCVR, and unfortunately, that wouldn't work as well. I've noticed that whenever I move, my arms are teleported back to my shoulders, yet I still cannot see them. However, whenever I try opening a door, pick up an object, etc. - the hitboxes are fine, it's just about the bones in the model.

**Comment by JTMCDev** [comment]
What headset are you using. also emote mods do not work so uninstall that

**Comment by DaXcess** [comment]
> Greetings! Found this mod as an interesting thing to try out, but I met an issue - I couldn't see my arms. And I thought that it was a normal thing to deal with, but when I looked up - boom! I saw my arms. I thought of deleting a few mods that could interfere with the player's model bones, but that didn't work. I tried deleting every single mod except LCVR, and unfortunately, that wouldn't work as well. I've noticed that whenever I move, my arms are teleported back to my shoulders, yet I still cannot see them. However, whenever I try opening a door, pick up an object, etc. - the hitboxes are fine, it's just about the bones in the model.

This sounds exactly like an emote mod issue, though you mentioned that you also tried without any emote mods. If you run a complete clean install of LCVR (If using r2modman, create new profile with only BepInEx + LCVR, nothing else / If using steam, delete the `BepInEx` folder and reinstall bepinex + LCVR) and are still experiencing the issue, could you send your log files here?

**Comment by Ouija1733** [comment]
Same issue here: Im trying to use this mod with the most lethal company modpack (on the latest version of the pack and the game making the "check version" funtion returning true regardless) and my arms are on the top of the ship. Any fix?

**Comment by DaXcess** [comment]
This is a mod incompatibility issue
