### ISSUE TITLE
VR HUD

### ISSUE THREAD

**Issue by DaXcess** [DaXcess/LCVR#4]
Since the entire hierarchy of the HUD rendering has changed, there is a need for some changes to allow the HUD to be viewed correctly. I have a few ideas of how to implement some parts of this:

- [x] Have the battery meter show on and track the right arm when a battery powered object is being held
- [x] Have the sprint/character icon show on and track the left arm
- [x] Display interact icons on the objects themselves instead of in front of the camera
- [x] Object scanner
- [x] Misc camera tracked HUD 
- [x] Configuration option to track arm based HUD on camera instead of arms
- [ ] Inventory?

**Comment by Tyler8x** [comment]
for the pause menu, a floating screen seems like the best option to me, and I was thinking for the post-game summary you could either do something similar or display the info on a poster on the ship?

**Comment by yusuf-wadi** [comment]
Post-game and you have been fired can be displayed some distance away from the players head like the bootup menu from the commit before the most recent. inventory can be on your left arm somewhere. on the right arm, i suggest sprint and character icon and batter meter be displayed on the underside of the wrist and the time should be displayed on the top-side of the wrist like a watch.

**Comment by Vyppal** [comment]
don't forget the players wear visors, and by the looks of things, it appears that there's meant to be a digital overlay (mainly displayed through the scanning mechanic, and notifications, as well as the recently added signal transmitter). If you can get good positioning u can still use the same display

**Comment by DaXcess** [comment]
> don't forget the players wear visors, and by the looks of things, it appears that there's meant to be a digital overlay (mainly displayed through the scanning mechanic, and notifications, as well as the recently added signal transmitter). If you can get good positioning u can still use the same display

Visor is disabled in VR at this moment, as it was not following the head rotation correctly (left/right worked, up/down did not). But this idea would be a lot easier to implement (I believe)

**Comment by ggezgaming** [comment]
> don't forget the players wear visors, and by the looks of things, it appears that there's meant to be a digital overlay (mainly displayed through the scanning mechanic, and notifications, as well as the recently added signal transmitter). If you can get good positioning u can still use the same display

The issue with having a screen wide hud in VR is accessibility, as someone who only has 1 eye that works it would be really annoying if the entire right side of the hud just didn't exist for me, with my limited FOV i can still see in-world huds since i can just bring my arms up to my face or whatnot, but with a static camera-based hud we would run into issues

**Comment by DaXcess** [comment]
> > don't forget the players wear visors, and by the looks of things, it appears that there's meant to be a digital overlay (mainly displayed through the scanning mechanic, and notifications, as well as the recently added signal transmitter). If you can get good positioning u can still use the same display
> 
> The issue with having a screen wide hud in VR is accessibility, as someone who only has 1 eye that works it would be really annoying if the entire right side of the hud just didn't exist for me, with my limited FOV i can still see in-world huds since i can just bring my arms up to my face or whatnot, but with a static camera-based hud we would run into issues

The most important pieces of the HUD are arm-tracked (sprint, health, battery, weight). Other UI, like the interaction overlay and the object scanner is world-tracked so that shouldn't be a problem too. The rest of the UI will most likely be camera-tracked (head-tracked) since there is just no better place to put these. These are things like the object scanner total scrap value, alert/tips ui, radiation ui, critical injury ui, end-of-day results. But imo these are less important and I think it's best not to put too much focus on those and focus on more important bits to get the mod to an initial release.

**Comment by XxsjrapsxX** [comment]
i had a quick question. Will there be an option for sprinting to be based off head where your head is looking? I find arm tracked is cool but i normally prefer head based movement as it feels slightly more natural

**Comment by DaXcess** [comment]
> i had a quick question. Will there be an option for sprinting to be based off head where your head is looking? I find arm tracked is cool but i normally prefer head based movement as it feels slightly more natural

The mod will get a configuration option called something like "disableArmBasedHud" which can be toggled to have all the HUD tracked to the camera instead of some of it being tracked to the arms. I'm still debating on whether this option should also affect the HUD when hovering over an interactable item (e.g. light switch, lever, scrap) as that HUD is currently rendered at the location of the item and not on the camera. The HUD for the object scanner will definitely always be tracked on the items you scanned otherwise the entire feature starts not making sense.

**Comment by DaXcess** [comment]
![image](https://github.com/DaXcess/LCVR/assets/46288749/47bb302d-86f5-4223-9a83-3808ebd33a0a)

Boom, added
