### ISSUE TITLE
Animations being broken for PC players

### ISSUE THREAD

**Issue by JTMCDev** [DaXcess/LCVR#40]
Being on VR and friends being on PC the default animations are broken. they just stand still. and same for people who dont have a VR player in the lobby the animations just dont work

**Comment by JTMCDev** [comment]
I mean animations being serversided stop working

**Comment by DaXcess** [comment]
Just tested this on the latest build without any other mods, no issues on that front. Also works when combined with TooManyEmotes (latest version contains a config so that it works in VR), in a combined lobby of VR players and non-vr players (Both with the VR and without the VR mod)

**Comment by JTMCDev** [comment]
Amazing! Thank you!
