### ISSUE TITLE
Getting stuck on multiplayer selection.

### ISSUE THREAD

**Issue by presto1241** [DaXcess/LCVR#41]
I got a friend who is using an Oculus rift CV1. He can launch into the game just fine, but the game doesn't seem to load the UI in world-space and still tries to run screen-space (The same as normal desktop). Breaking the ability to navigate anything. He does have the OpenXR runtime set correctly, he also tried to use Oculus and SteamVR separately but had the same outcome on both. Below is what the logs spit out:
![image](https://github.com/DaXcess/LCVR/assets/76562804/a0be997e-9eb7-486b-98e0-0a5ce78bef44)

We both are using the same LCVR files and I'm having no issues.

**Comment by DaXcess** [comment]
When you're diagnosing issues, try to enable the Debug log level (inside the BepInEx.cfg file), since that is disabled by default. Most of the logging done by LCVR is on the Debug level.

**Comment by presto1241** [comment]
He hasn't gotten back to me. But I updated to the latest version of the mod yesterday (Game version was still v45 not v48). And noticed I was able to repro his issue if I didn't include the HD_Render_Pipeline core dll file in the runtime Dependencies. So something tells me it has to do with that for now. Only annoying part is if I do include the file then I get an error every frame saying:
`Exception: Blitter is already initialized. Please only initialize the blitter once or you will leak engine resources. If you need to re-initialize the blitter with different shaders destroy & recreate it.
  at UnityEngine.Rendering.Blitter.Initialize (UnityEngine.Shader blitPS, UnityEngine.Shader blitColorAndDepthPS) [0x0000d] in <3e4d5d98dfc34520bf7c624af5a98275>:IL_000D 
  at UnityEngine.Rendering.HighDefinition.HDRenderPipeline..ctor (UnityEngine.Rendering.HighDefinition.HDRenderPipelineAsset asset) [0x00998] in <6214bbc46efe4329a4e9806065941bb4>:IL_0998 
  at UnityEngine.Rendering.HighDefinition.HDRenderPipelineAsset.CreatePipeline () [0x00000] in <6214bbc46efe4329a4e9806065941bb4>:IL_0000 
  at UnityEngine.Rendering.RenderPipelineAsset.InternalCreatePipeline () [0x00004] in <e27997765c1848b09d8073e5d642717a>:IL_0004 
UnityEngine.DebugLogHandler:Internal_LogException(Exception, Object)
UnityEngine.DebugLogHandler:LogException(Exception, Object)
UnityEngine.Logger:LogException(Exception, Object)
UnityEngine.Debug:LogException(Exception)
UnityEngine.Rendering.RenderPipelineAsset:InternalCreatePipeline()
UnityEngine.Rendering.RenderPipelineManager:PrepareRenderPipeline(RenderPipelineAsset)
UnityEngine.Rendering.RenderPipelineManager:DoRenderLoop_Internal(RenderPipelineAsset, IntPtr, Object)`

And I believe it results in a crash or at least a softlock. This error starts happening after the unity splashscreen but before the multiplayer selection UI loads.

**Comment by DaXcess** [comment]
> He hasn't gotten back to me. But I updated to the latest version of the mod yesterday (Game version was still v45 not v48). And noticed I was able to repro his issue if I didn't include the HD_Render_Pipeline core dll file in the runtime Dependencies. So something tells me it has to do with that for now. Only annoying part is if I do include the file then I get an error every frame saying: `Exception: Blitter is already initialized. Please only initialize the blitter once or you will leak engine resources. If you need to re-initialize the blitter with different shaders destroy & recreate it. at UnityEngine.Rendering.Blitter.Initialize (UnityEngine.Shader blitPS, UnityEngine.Shader blitColorAndDepthPS) [0x0000d] in <3e4d5d98dfc34520bf7c624af5a98275>:IL_000D at UnityEngine.Rendering.HighDefinition.HDRenderPipeline..ctor (UnityEngine.Rendering.HighDefinition.HDRenderPipelineAsset asset) [0x00998] in <6214bbc46efe4329a4e9806065941bb4>:IL_0998 at UnityEngine.Rendering.HighDefinition.HDRenderPipelineAsset.CreatePipeline () [0x00000] in <6214bbc46efe4329a4e9806065941bb4>:IL_0000 at UnityEngine.Rendering.RenderPipelineAsset.InternalCreatePipeline () [0x00004] in <e27997765c1848b09d8073e5d642717a>:IL_0004 UnityEngine.DebugLogHandler:Internal_LogException(Exception, Object) UnityEngine.DebugLogHandler:LogException(Exception, Object) UnityEngine.Logger:LogException(Exception, Object) UnityEngine.Debug:LogException(Exception) UnityEngine.Rendering.RenderPipelineAsset:InternalCreatePipeline() UnityEngine.Rendering.RenderPipelineManager:PrepareRenderPipeline(RenderPipelineAsset) UnityEngine.Rendering.RenderPipelineManager:DoRenderLoop_Internal(RenderPipelineAsset, IntPtr, Object)`
> 
> And I believe it results in a crash or at least a softlock. This error starts happening after the unity splashscreen but before the multiplayer selection UI loads.

Yeah that's an issue with loading the HD render pipeline assembly twice (once by Unity, once by the mod). It's also thereby **not** a runtimedep.
