### ISSUE TITLE
Inventory scrolling very hard.

### ISSUE THREAD

**Issue by JTMCDev** [DaXcess/LCVR#42]
Scrolling through your inventory 1 by 1 does not work. We should be able to simply point our right thumbstick up once and it will go once. Currently keeping it up will scroll through very fast. Instead, we should have it where if you keep it up it should stop.

**Comment by DaXcess** [comment]
This is already how the base mod works. Other mods might mess with it though and some of them have been documented messing up the speed at which the scroll is.
