### ISSUE TITLE
when i launch lethal company it says "unsupported game version or game file was curropted" it launches and i can play but the vr version doesnt show up. i need help please!!

### ISSUE THREAD

**Issue by FemboyAzura** [DaXcess/LCVR#43]
when i launch lethal company it says "unsupported game version or game file was curropted" it launches and i can play but the vr version doesnt show up. i need help please!!

**Comment by Phil25** [comment]
Where did you download the mod from?

**Comment by CookieTheWookie** [comment]
It's due to the new update today. This mod is for v45, the current version is v47.

**Comment by BobNxtUp** [comment]
Go to steam library right click lethal company go to properties -> betas -> beta participation -> previous. And this will work, because lethal company's most recent update broke this mod.

**Comment by DaXcess** [comment]
> when i launch lethal company it says "unsupported game version or game file was curropted" it launches and i can play but the vr version doesnt show up. i need help please!!

That's the mod's "Game Integrity Check" working. If it detects an unknown version of the game it disables itself, and this is currently happening due to the V47 update.

**Comment by GuiOliv** [comment]
> > when i launch lethal company it says "unsupported game version or game file was curropted" it launches and i can play but the vr version doesnt show up. i need help please!!
> 
> That's the mod's "Game Integrity Check" working. If it detects an unknown version of the game it disables itself, and this is currently happening due to the ~V47~ ~V48~ V49 update.

Is it possible to disable the Game Integrity Check?

**Comment by Xavienth** [comment]
> Is it possible to disable the Game Integrity Check?

Yes but when I tested it, it did not appear to solve the issue. You'll have to wait for the mod to be updated.

**Comment by DaXcess** [comment]
Newest versions of the mod target the latest game version

**Comment by GenerousGendalf** [comment]
I'm currently having this problem with my HTC Vive, any help please? I've used r2Modmanager, and tried manually installing it as well, but VR version still will not appear.
