### ISSUE TITLE
skips loading openxr_loader.dll and UnityOpenXR.dll

### ISSUE THREAD

**Issue by Katz-sz** [DaXcess/LCVR#44]
im on v45 and it just keeps saying this, it was working fine yesterday, i even disabled all mods but this and recompiled with the new version but issue still occured, and whenever i join people can hear my voice but cant see me and vice versa, even if they dont have the vr mod, and all i see is the UI and a black screen when in another person's lobby, and also the main menu looks weird in my left lens, I have also tried uninstalling and re installing already but no luck
![Screenshot 2024-01-08 211653](https://github.com/DaXcess/LCVR/assets/156040832/ac61a6a2-e12e-4a71-a1bc-25f4d6d7783a)

**Comment by Katz-sz** [comment]
![Screenshot 2024-01-09 000057](https://github.com/DaXcess/LCVR/assets/156040832/bded530c-075b-4dea-abd7-e2ef792b714e)
possibly related?

**Comment by Katz-sz** [comment]
![dffddsffds](https://github.com/DaXcess/LCVR/assets/156040832/d89818c9-2eda-41ec-84c4-842729243461)
Possibly related?

**Comment by Maloonkey** [comment]
No, this is likely to do with the fact that Lethal Company updated today.

**Comment by DaXcess** [comment]
> im on v45 and it just keeps saying this, it was working fine yesterday, i even disabled all mods but this and recompiled with the new version but issue still occured, and whenever i join people can hear my voice but cant see me and vice versa, even if they dont have the vr mod, and all i see is the UI and a black screen when in another person's lobby, and also the main menu looks weird in my left lens, I have also tried uninstalling and re installing already but no luck
> ![Screenshot 2024-01-08 211653](https://github.com/DaXcess/LCVR/assets/156040832/ac61a6a2-e12e-4a71-a1bc-25f4d6d7783a)
> 

All warnings were temporarily enabled to test text alignment. This is an unfinished product after all
