### ISSUE TITLE
Broken on patch 47

### ISSUE THREAD

**Issue by Choochoo251** [DaXcess/LCVR#47]
Got working just hours before the new patch, fresh reinstall of LC and LCVR and no luck. During recompiling, getting the following error "string" (not used to reporting or propper terminology, please forgive):

"
[...]
C:\Users\jdomi\Desktop\LCVR-main\Patches\PlayerControllerPatches.cs(219,29): error CS0111: Type 'PlayerControllerPatche
s' already defines a member called 'ClickHoldInteractionPrefix' with the same parameter types [C:\Users\jdomi\Desktop\L
CVR-main\LCVR.csproj]
C:\Users\jdomi\Desktop\LCVR-main\Patches\PlayerControllerPatches.cs(226,29): error CS0111: Type 'PlayerControllerPatche
s' already defines a member called 'OnPlayerDeath' with the same parameter types [C:\Users\jdomi\Desktop\LCVR-main\LCVR
.csproj]
C:\Users\jdomi\Desktop\LCVR-main\Patches\PlayerControllerPatches.cs(241,29): error CS0111: Type 'PlayerControllerPatche
s' already defines a member called 'OnPlayerRevived' with the same parameter types [C:\Users\jdomi\Desktop\LCVR-main\LC
VR.csproj]
C:\Users\jdomi\Desktop\LCVR-main\Patches\PlayerControllerPatches.cs(255,29): error CS0111: Type 'PlayerControllerPatche
s' already defines a member called 'SwitchedToItemSlot' with the same parameter types [C:\Users\jdomi\Desktop\LCVR-main
\LCVR.csproj]
C:\Users\jdomi\Desktop\LCVR-main\Patches\PlayerControllerPatches.cs(277,29): error CS0111: Type 'PlayerControllerPatche
s' already defines a member called 'IsInactivePlayer' with the same parameter types [C:\Users\jdomi\Desktop\LCVR-main\L
CVR.csproj]
    0 Warning(s)
    428 Error(s)
"

**Comment by CookieTheWookie** [comment]
Just downgrade to previous version, and it should work.
Steam Library > Settings > Properties > Betas > Beta participation.
Unfortunately for now it will only work on V45 (previous version) until this is updated. 
The creator is currently working on fully releasing, and will work on updating it after. 
"V49 support gonna be fixed soon, have been working on release preps so no code updates for a bit" - DaXcess, YT comment section, video - https://www.youtube.com/watch?v=08LX0EQ5-Zc

**Comment by alexderpyfox** [comment]
best to update it to latest before release because not a lot will use the old version anymore if any

**Comment by bontebok** [comment]
> best to update it to latest before release because not a lot will use the old version anymore if any

It was nearly 4am when I wrote that. I meant V49, derp :)

**Comment by CookieTheWookie** [comment]
It’s worth downgrading. Some people still play on v45. Plus, with how easy it is to downgrade, it’s easy for people you often play with to downgrade. Not like you are missing too much between v45 and v47 either. Nothing in v47 is really needed.

**Comment by JTMCDev** [comment]
I'd still just wait for the code patch. DaXcess seems like he's working on it right now.

**Comment by CookieTheWookie** [comment]
Well yeah, if you don’t have anything done, or don’t have time at the moment, then wait. Though, if you are desperate to check it out, like i was, it’s not too hard to just downgrade it, then just update it when new code is released.

**Comment by DaXcess** [comment]
This looks like the project directory is just completely broken on your end. Try recloning it into a fresh new project and it should be fixed.
