### ISSUE TITLE
error when I start the game

### ISSUE THREAD

**Issue by ena0** [DaXcess/LCVR#54]
Hey,

When I start the game, whennever in v47 ou v45, in VR or not I have an error that spawn and the game donesn't launch in vr mode

`[Warning:      LCVR] ==== OpenXR Init Info ====

Stage 1 Missing Entry Points: (1)
  xrInitializeLoaderKHR

==== OpenXR Provider Info ====

Spec Version: 1.0.27
Provider Version: 1.8.2
App: Lethal Company #3159629941
Engine: 2022.3.9f1 #53515265

==== OpenXR Runtime Info ====

Features requested to be enabled: (7)
  : Version=, Company=""
  : Version=, Company=""
  : Version=, Company=""
  : Version=, Company=""
  : Version=, Company=""
  : Version=, Company=""
  : Version=, Company=""

Requested feature extensions not supported by runtime: (0)

Available Runtime Extensions: (29)
  XR_KHR_D3D11_enable: Version=9
  XR_KHR_D3D12_enable: Version=9
  XR_KHR_opengl_enable: Version=10
  XR_KHR_vulkan_enable: Version=8
  XR_KHR_vulkan_enable2: Version=2
  XR_KHR_composition_layer_depth: Version=6
  XR_KHR_win32_convert_performance_counter_time: Version=1
  XR_KHR_convert_timespec_time: Version=1
  XR_KHR_composition_layer_cube: Version=8
  XR_KHR_composition_layer_cylinder: Version=4
  XR_KHR_composition_layer_equirect: Version=3
  XR_KHR_visibility_mask: Version=2
  XR_KHR_composition_layer_color_scale_bias: Version=5
  XR_EXT_win32_appcontainer_compatible: Version=1
  XR_EXT_debug_utils: Version=5
  XR_OCULUS_recenter_event: Version=1
  XR_OCULUS_audio_device_guid: Version=1
  XR_FB_color_space: Version=3
  XR_FB_display_refresh_rate: Version=1
  XR_META_performance_metrics: Version=2
  XR_META_headset_id: Version=1
  XR_OCULUS_ovrsession_handle: Version=1
  XR_EXT_local_floor: Version=1
  XR_FB_haptic_amplitude_envelope: Version=1
  XR_FB_haptic_pcm: Version=1
  XR_FB_touch_controller_pro: Version=1
  XR_META_touch_controller_plus: Version=1
  XR_FB_touch_controller_proximity: Version=1
  XR_OCULUS_external_camera: Version=1

Available Layers: (0)

Runtime Name: Oculus
Runtime Version: 1.92.0

==== OpenXR Exception Thrown ====

Error: XrResult failure [XR_ERROR_FORM_FACTOR_UNAVAILABLE]
    Origin: result
    Source: C:\build\output\unity\xr.sdk.openxr\NativePlugin\Source\unity_session.cpp:260

==== Std Exception Thrown ====

Function: Display_Initialize
Message: XrResult failure [XR_ERROR_FORM_FACTOR_UNAVAILABLE]
    Origin: result
    Source: C:\build\output\unity\xr.sdk.openxr\NativePlugin\Source\unity_session.cpp:260

==== Last 20 non-XR_SUCCESS returns ====
[FAILURE] xrGetSystem: XR_ERROR_FORM_FACTOR_UNAVAILABLE (1x)

==== Last 20 Events ====

[Error  :      LCVR] Failed to start in VR Mode! Only Non-VR features are available!
[Error  :      LCVR] An OpenXR log dump is displayed above to help with troubleshooting.`

Did I forget to do something when I build in visual studio or get the files in unity ?

**Comment by ena0** [comment]
OK, I’ll try again to launch the game but with oculus airlink and not steamLink and it works when I launch the game with thunderstore, so I don’t know if it’s a mod or steam mistake

**Comment by DaXcess** [comment]
> OK, I’ll try again to launch the game but with oculus airlink and not steamLink and it works when I launch the game with thunderstore, so I don’t know if it’s a mod or steam mistake
> 
> thanks
> 
> PS: it work also with V49

Aah no this was an issue with which runtime you were using. If you are using Steam Link, you are using SteamVR, but the game tried to use Oculus, which means that indeed the game would not detect the headset.

Glad you were able to fix it.

**Comment by agmass** [comment]
Hi, I'm having the exact same error with ALVR and linux. I cannot use oculus airlink as linux does not have the oculus software. Is there any way to get the game playing with steamvr?
