### ISSUE TITLE
remove morecompany code because it no longer is open source

### ISSUE THREAD

**Issue by alexderpyfox** [DaXcess/LCVR#56]
because of this playing with people that have the morecompany mod seperately will result in incompatabilities because the morecompany code that is in lcvr no longer can be updated since the source is no longer available
 so its good to have morecompany mod being seperate so anyone that has morecompany has the same morecompany and will not be limited to lcvr mod  only specifically so people can play lcvr with people that dont have lcvr but do got morecompany mod seperately

**Comment by yusuf-wadi** [comment]
sentences are pretty cool.

**Comment by alexderpyfox** [comment]
maybe keep some essential parts of the code but so that the morecompany mod as seperate thing will still work with lcvr so that when you install morecompany seperaterly itll use that to play with others

**Comment by DaXcess** [comment]
There is no MoreCompany code in LCVR, it's LCVR's code that helps this mod be compatible with MoreCompany
