### ISSUE TITLE
Found 1 visual and 1 critical bug with mods

### ISSUE THREAD

**Issue by Fandovec03** [DaXcess/LCVR#57]
While testing compatability with friend's modpack I ran into problems with 2 mods in the modpack. By trial and error I found which mods were causing the issue.

The less serious issue is menu screen view duplication where each eye recieves it's own screen instead of blending into eachother. This was caused by MoreCompany mod. Upon loading the save the issue disappears. Probably because the changes mod does to UI.

The more serious issue is causing TooManyEmotes mod. Upon loading the save the screen freezes after few moments. The game runs normally otherwise. You hear the speaker, run, interact with stuff. The screen is stuck shaking like if you lagged in VRChat. There seems to be problem with either character's skeleton or the camera. Are the two mods fighting eachother?

**Comment by Fandovec03** [comment]
This is the error that is popping up:
[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
LCVR.Player.IKRigFollowVRRig.LateUpdate () (at <49d163701ed7400587a631e39d494325>:IL_0035)

**Comment by DaXcess** [comment]
Any mod other than MoreCompany has no official support in this mod (At the moment you might be running a version of MoreCompany that is not recognized by the mod, currently this mod expects MoreCompany 1.7.4).

**Comment by Fandovec03** [comment]
Still good to report the issue so they may be fixed in the future. I was running MoreCompany 1.7.4 and yet I had the split screens on main menu. If it helps I was running the game on quest 2.
