### ISSUE TITLE
Unable to open in vr mode

### ISSUE THREAD

**Issue by HaZe-UG** [DaXcess/LCVR#58]
I tried to set it all up, the set up worked however launching the game, it says failed to start in vr mode and launches as if im playing on pc. Quest 3 using steam vr

**Comment by ena0** [comment]
I already make an issue for that (It has since been closed), you need to use meta airlink and launcher the game with thunderstore

**Comment by CookieTheWookie** [comment]
You don’t need to specifically use meta airlink, just quest link, through cord.

Also if that doesn’t work either could you give more info.

**Comment by ena0** [comment]
The mod work properly with the v49 of LC, I didn't try to launch the game with Steam so I don't know if it work with meta link

**Comment by CookieTheWookie** [comment]
If you try to launch it with v49 the mod disables itself, because it isn’t optimized for it. So, you have to downgrade it to v45. It works with meta link, all you really have to do is connect it to your pc, then launch modded lc with r2modman.

**Comment by HaZe-UG** [comment]
I was launching the game on thunderstore app and using steam vr wireless on v45.

**Comment by CookieTheWookie** [comment]
Try with a cord, but first, when launching the game with modman, check the error on the second tab with lethal, it pops up when you launch modded. It should say why its not starting in vr mode.

**Comment by HaZe-UG** [comment]
> Try with a cord, but first, when launching the game with modman, check the error on the second tab with lethal, it pops up when you launch modded. It should say why its not starting in vr mode.

Do i have to use modman? My friends got it to work with thunder store

**Comment by ena0** [comment]
> I was launching the game on thunderstore app and using steam vr wireless on v45.  I tried with airlink but it would do a 2d screen and not vr mode either

All the menus of the game remain in 2d

**Comment by HaZe-UG** [comment]
> > I was launching the game on thunderstore app and using steam vr wireless on v45.  I tried with airlink but it would do a 2d screen and not vr mode either
> 
> All the menus of the game remain in 2d

Even in the game, playing, it wouldnt go into vr mode

**Comment by CookieTheWookie** [comment]
Its supposed to go into vr mode immediately so, even with the loading screens, you will know if it worked.

**Comment by ena0** [comment]
> > > I was launching the game on thunderstore app and using steam vr wireless on v45.  I tried with airlink but it would do a 2d screen and not vr mode either
> > 
> > All the menus of the game remain in 2d
> 
> Even in the game, playing, it wouldnt go into vr mode

Do you have any error in the BepInEx terminal when you launch the game in VR mode ?

**Comment by HaZe-UG** [comment]
> > > > I was launching the game on thunderstore app and using steam vr wireless on v45.  I tried with airlink but it would do a 2d screen and not vr mode either
> > > 
> > > 
> > > All the menus of the game remain in 2d
> > 
> > 
> > Even in the game, playing, it wouldnt go into vr mode
> 
> Do you have any error in the BepInEx terminal when you launch the game in VR mode ?

I can provide this tomorrow, my pc and vr are off rn, it would just say unable to launch in vr mode

**Comment by CookieTheWookie** [comment]
I would try using a cord. If you can’t it’s either it didn’t downgrade (make sure it says Lethal Company [previous]), or you didn't install the mod correctly.

**Comment by CookieTheWookie** [comment]
So are you using the steamvr app on the quest? Or going in meta airlink, then going into steamvr.

**Comment by HaZe-UG** [comment]
Going right i to steam vr

**Comment by CookieTheWookie** [comment]
> Going right i to steam vr

Yeah, then try without steamvr, you can just launch lethal company through modman with the vr connected, it should work. Steamvr may be interfering. Also, i highly recommend using a cord, but if it’s running completely fine (TEACH ME LOL) then, i guess you could continue using it.

**Comment by HaZe-UG** [comment]
> > Going right i to steam vr
> 
> Yeah, then try without steamvr, you can just launch lethal company through modman with the vr connected, it should work. Steamvr may be interfering. Also, i highly recommend using a cord, but if it’s running completely fine (TEACH ME LOL) then, i guess you could continue using it.

Ill try without a cord and use modman, my wires are all super short, ill let you know how it goes

**Comment by CookieTheWookie** [comment]
> > > Going right i to steam vr
> > 
> > 
> > Yeah, then try without steamvr, you can just launch lethal company through modman with the vr connected, it should work. Steamvr may be interfering. Also, i highly recommend using a cord, but if it’s running completely fine (TEACH ME LOL) then, i guess you could continue using it.
> 
> Ill try without a cord and use modman, my wires are all super short, ill let you know how it goes

I recommend usb-c cords on amazon.

Wait so to confirm, you were using airlink, steamvr, without a cord, and with modman yes?

**Comment by HaZe-UG** [comment]
> > > > Going right i to steam vr
> > > 
> > > 
> > > Yeah, then try without steamvr, you can just launch lethal company through modman with the vr connected, it should work. Steamvr may be interfering. Also, i highly recommend using a cord, but if it’s running completely fine (TEACH ME LOL) then, i guess you could continue using it.
> > 
> > 
> > Ill try without a cord and use modman, my wires are all super short, ill let you know how it goes
> 
> I recommend usb-c cords on amazon.
> 
> Wait so to confirm, you were using airlink, steamvr, without a cord, and with modman yes?

I was only using steam vr and thunderstore

**Comment by CookieTheWookie** [comment]
> > > > > Going right i to steam vr
> > > > 
> > > > 
> > > > Yeah, then try without steamvr, you can just launch lethal company through modman with the vr connected, it should work. Steamvr may be interfering. Also, i highly recommend using a cord, but if it’s running completely fine (TEACH ME LOL) then, i guess you could continue using it.
> > > 
> > > 
> > > Ill try without a cord and use modman, my wires are all super short, ill let you know how it goes
> > 
> > 
> > I recommend usb-c cords on amazon.
> > Wait so to confirm, you were using airlink, steamvr, without a cord, and with modman yes?
> 
> I was only using steam vr and thunderstore

Can you tell me the exact process you used to set it up? Also but thunderstore, do you mean the thunderstore software? (R2modman)

**Comment by HaZe-UG** [comment]
> > > > > > Going right i to steam vr
> > > > > 
> > > > > 
> > > > > Yeah, then try without steamvr, you can just launch lethal company through modman with the vr connected, it should work. Steamvr may be interfering. Also, i highly recommend using a cord, but if it’s running completely fine (TEACH ME LOL) then, i guess you could continue using it.
> > > > 
> > > > 
> > > > Ill try without a cord and use modman, my wires are all super short, ill let you know how it goes
> > > 
> > > 
> > > I recommend usb-c cords on amazon.
> > > Wait so to confirm, you were using airlink, steamvr, without a cord, and with modman yes?
> > 
> > 
> > I was only using steam vr and thunderstore
> 
> Can you tell me the exact process you used to set it up? Also but thunderstore, do you mean the thunderstore software? (R2modman)

https://youtu.be/08LX0EQ5-Zc?si=yMDTUdUAcoyb6gL7

I followed this guide to set it all up, the only one i could find

**Comment by CookieTheWookie** [comment]
> > > > > > > Going right i to steam vr
> > > > > > 
> > > > > > 
> > > > > > Yeah, then try without steamvr, you can just launch lethal company through modman with the vr connected, it should work. Steamvr may be interfering. Also, i highly recommend using a cord, but if it’s running completely fine (TEACH ME LOL) then, i guess you could continue using it.
> > > > > 
> > > > > 
> > > > > Ill try without a cord and use modman, my wires are all super short, ill let you know how it goes
> > > > 
> > > > 
> > > > I recommend usb-c cords on amazon.
> > > > Wait so to confirm, you were using airlink, steamvr, without a cord, and with modman yes?
> > > 
> > > 
> > > I was only using steam vr and thunderstore
> > 
> > 
> > Can you tell me the exact process you used to set it up? Also but thunderstore, do you mean the thunderstore software? (R2modman)
> 
> https://youtu.be/08LX0EQ5-Zc?si=yMDTUdUAcoyb6gL7
> 
> I followed this guide to set it all up, the only one i could find

But for the vr, how exactly do you connect it to your pc?

**Comment by HaZe-UG** [comment]
I was struggling with that, i was using steam vr only on my pc and quest

**Comment by CookieTheWookie** [comment]
> I was struggling with that, i was using steam vr only on my pc and quest

How exactly?

**Comment by DaXcess** [comment]
Troubleshooting these kind of errors without logs is impossible. Long story short: I think you're using the wrong OpenXR runtime, one that doesn't detect your headset.

**Comment by HaZe-UG** [comment]
> > I was struggling with that, i was using steam vr only on my pc and quest
> 
> How exactly?

so i had steam vr downloaded on my vr, and on my pc, and you connect through that, i tried it just now and somehow it decided to work
