### ISSUE TITLE
Unable to find package HarmonyX

### ISSUE THREAD

**Issue by the-broz** [DaXcess/LCVR#60]
As of downloading the latest source code and attempting to compile the following error is sent to the console.

`error NU1101: Unable to find package HarmonyX. No packages exist with this id in s ource(s): BepInEx, Microsoft Visual Studio Offline Packages`

**Comment by Xavienth** [comment]
Visual Studio tries to get the required packages automatically, but you don't have the source you need where it can find the libraries.

You'll want to open the nuget package manager from the project tab in the title bar and add nuget as a source, see here https://learn.microsoft.com/en-us/nuget/consume-packages/install-use-packages-visual-studio#package-sources

**Comment by DaXcess** [comment]
Your visual studio is not using the BepInEx nuget repository, this should work by default when opening the project. Try redownloading the project again or checking whether your VS install is corrupt or not.
