### ISSUE TITLE
Unplayable lag for the Quest

### ISSUE THREAD

**Issue by K3ag** [DaXcess/LCVR#64]
Quest player, when I boot up the mod, even with all my mods that are compatible and vanilla Lethal. The game is very laggy that its unplayable. I've noticed when taking off the headset ingame FPS normalizes to 144.

**Comment by jonafinmicclen** [comment]
What is ur specs?

**Comment by K3ag** [comment]
> What is ur specs?
![image_2024-01-12_193739567](https://github.com/DaXcess/LCVR/assets/156483827/14a1ae32-8aa0-4aa4-98f8-0bdce7c75a44)

**Comment by jonafinmicclen** [comment]
I can't say 100% but 1060 sounds weak for this mod, I know the original game requires only 1050 but rendering for a vr headset is more resource intensive than for a flat screen (two screens basically).

**Comment by DaXcess** [comment]
A 1060 would really struggle with this mod yeah, only saving grace is dynamic resolution (without dlss as I dont think that's even supported on the 1060 yet)

**Comment by Jananas13035** [comment]
i have a 1660 super and it still lags on quest :c

**Comment by Jananas13035** [comment]
updated drivers and now no lag yippee

**Comment by WEEZOOKARP** [comment]
i still lag using framerate booster mods with 
Windows 10 22h2
an overclocked 3050
i5 8400 running 3.7ghz (AtlasOS)
32gb 2666mhz ram
installed on a samsung 860 evo with over 30gb free
im on quest 2 using alvr to emulate steamvr (runs so much smoother than oculus's dogshit)
my setup can run blade and sorcery at highest and still stays above 90fps but i get nearly 20ms frametimes on lethal with vr on
