### ISSUE TITLE
Game runs bad in VR but looks fine on recording and on my monitor

### ISSUE THREAD

**Issue by MastraDaMasta** [DaXcess/LCVR#66]
I use and oculus quest 2 and a KIWI cord to connect to my PC I also use a 3.0 USB slot. When I'm playing in VR and move my head, Walk, Or lean the screen shakes like crazy, I'm not sure what's causing the problem cause I'm pretty sure my PC can run it when I check my task manager while the game was open and I was playing nothing was at 100% usage I don't know if that means anything but yea.

PC Specs:
![Screenshot 2024-01-12 220004](https://github.com/DaXcess/LCVR/assets/121995512/713b2bea-c5c5-4cfb-8171-ad92619ffa3d)

**Comment by DaXcess** [comment]
SteamVR + this mod + a lower end graphics card = shaking. I've seen this happen with multiple users and the best way to fix it is to not use SteamVR, but Oculus (Air)link in your case

**Comment by MastraDaMasta** [comment]
> SteamVR + this mod + a lower end graphics card = shaking. I've seen this happen with multiple users and the best way to fix it is to not use SteamVR, but Oculus (Air)link in your case

how do you skip steamVR? don't you need to use it for steam games? when I close steamVR after it opens automatically it just closes both steamVR and lethal company.

**Comment by bavninja** [comment]
Go to oculus settings for openXR and set it as default there, in the discord you'll be able to find a screenshot in FAQ 2

**Comment by heavygee** [comment]
[https://medium.com/@h34vyg33/optimizing-the-performance-of-liv-for-streaming-vr-content-d8b0674b0724 ](https://medium.com/@h34vyg33/optimizing-the-performance-of-liv-for-streaming-vr-content-d8b0674b0724) this article is targeted at Liv for vr content recording, but the practices to follow to get to performance for your setup apply here - in short, "turn everything way down", this shows you how and where.

When you run VR, you're asking your system for over 200% of what flatscreen demands.
