### ISSUE TITLE
when i use voice chat i can only hear my friend for a second at random times

### ISSUE THREAD

**Issue by TerraMad01** [DaXcess/LCVR#67]
Me and my friend both installed the mod and when we got in i could only hear his voice for a second at random times and he could only hear me for a second at random times. we switched mics and everything and we still had the problem

**Comment by Jastro** [comment]
I have the same problem. 

We are 2 players, Quest 2 and Quest 3 VR players and we connect using Steam Link

**Comment by DaXcess** [comment]
Fixed in 1.0.1
