### ISSUE TITLE
Player hand locations appears significantly offset to other players

### ISSUE THREAD

**Issue by bontebok** [DaXcess/LCVR#68]
Using the latest version of LRVC, the adjusted IK system seemed to fix the first person arm issue, but may have introduced a significant offset to the hand locations.

![image](https://github.com/DaXcess/LCVR/assets/23562523/08298f27-1fae-4b34-9009-2063ef41edff)
![image](https://github.com/DaXcess/LCVR/assets/23562523/331f59e8-2577-4c65-8c29-b1c9e9acf412)

In the above two screenshots, this is a photo of two different players using Valve Index headsets and controllers holding their hands straight out in front with their arms parallel to the ground. In first person, their arms were shown in the correct position.

![image](https://github.com/DaXcess/LCVR/assets/23562523/b9a54d4f-a708-4285-841b-2a02a57fc98c)
![image](https://github.com/DaXcess/LCVR/assets/23562523/0b2b7907-e633-4e85-9ee2-1d3116580a97)

In the above photo, both players are holding their controllers as far left as possible, but in the photo they appear to still have their hands mostly on the left side. In first person, their arms were shown in the correct position.

The only Mods enabled during this test was BepinEx, LC_API, and LCVR compiled after the most recent commits were merged.

**Comment by DaXcess** [comment]
This has to do with not being in your play area center (offsets arent synced). This is fixed on my local end and will be pushed soon

**Comment by bontebok** [comment]
Ah, I had incorrectly assumed that the head location would be the offset used for the controllers. If you need any testing on the Index, hmu. Thanks!

**Comment by xupypg88** [comment]
![VirtualDesktop Android-20240114-180059](https://github.com/DaXcess/LCVR/assets/22127581/adc44e71-7231-42b4-8f55-3a6f64dd952f)

My 2 cents:
Oculus Quest 2 + Virtual Desktop.
I start Steam VR then the moded game via r2modman. The hands are floating a meter above my hand being still in one position.
Interactions with buttons are working fine and all hints appear.

**Comment by HyperVoidal** [comment]
> ![VirtualDesktop Android-20240114-180059](https://private-user-images.githubusercontent.com/22127581/296578885-adc44e71-7231-42b4-8f55-3a6f64dd952f.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUyOTg4NTMsIm5iZiI6MTcwNTI5ODU1MywicGF0aCI6Ii8yMjEyNzU4MS8yOTY1Nzg4ODUtYWRjNDRlNzEtNzIzMS00MmI0LThmNTUtM2E2ZjY0ZGQ5NTJmLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE1VDA2MDIzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI5ZDYxNzExNjA3MjY1MGI0NTllNWUzZjY0ZjVjMDkwNWYxOGE0ODJmYjM5ODI2ZTRjY2M1ZjVhM2JmNjdmNzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gzf7H-SS-Wyl40JZHxnFwwuVyDsGbqnW04QrsfuS2wk)
> 
> My 2 cents: Oculus Quest 2 + Virtual Desktop. I start Steam VR then the moded game via r2modman. The hands are floating a meter above my hand being still in one position. Interactions with buttons are working fine and all hints appear. I tried to center position in Steam and Quest, but the hands are still on the same height globally (not offset from my head) even if you center headset incorrectly (sitting for example)

I have the same issue, and I can't seem to fix it.

**Comment by Switek96** [comment]
> ![VirtualDesktop Android-20240114-180059](https://private-user-images.githubusercontent.com/22127581/296578885-adc44e71-7231-42b4-8f55-3a6f64dd952f.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzMDM1OTcsIm5iZiI6MTcwNTMwMzI5NywicGF0aCI6Ii8yMjEyNzU4MS8yOTY1Nzg4ODUtYWRjNDRlNzEtNzIzMS00MmI0LThmNTUtM2E2ZjY0ZGQ5NTJmLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE1VDA3MjEzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY0OGEyMjJiMzEyNzk0MWViMWQ0NzUxOWJlNWEwYjRmZDc5N2I3ODNlYjY4ZDVmNDliY2YxNjI2YzkzMjljN2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0wzrqvUnaHv_1VQivHLdTQfFvoMMEMABPg2iFvI6J-o)
> 
> My 2 cents: Oculus Quest 2 + Virtual Desktop. I start Steam VR then the moded game via r2modman. The hands are floating a meter above my hand being still in one position. Interactions with buttons are working fine and all hints appear. I tried to center position in Steam and Quest, but the hands are still on the same height globally (not offset from my head) even if you center headset incorrectly (sitting for example)

I had the same issue (with Valve Index). For me deleting MoreEmotes mod resolved it.
If this still don't work try testing every mod you're using, start only with MoreCompany in "plugins" folder.
I hope it helped somehow.

**Comment by xupypg88** [comment]
I've seen that other guy on Youtube used Oculus without an issue, so I tried again an made it work.

My workaround: 
1. Virtual Desktop - Settings (PC) OpenX Runtime - Set to "Steam VR"
![image](https://github.com/DaXcess/LCVR/assets/22127581/97b6581d-5228-4dc0-8d0c-7235afd63daf)

2. Set Oculus Boundaries to Standing experience (Not Room Scale).
3. Get rid of other mods or create a new profile with only one mode (LCVR).

Start Steam VR via Virtual Desktop then start the Moded game via the R2modman
