### ISSUE TITLE
Opens as pc not vr

### ISSUE THREAD

**Issue by Sapper1430** [DaXcess/LCVR#73]
I'm using quest air link to my pc and when I launch it doesn't appear in the headset. I just see the menu for link

**Comment by Sapper1430** [comment]
Also I am using r2modman if that hepls

**Comment by AimingForAlex** [comment]
check if your opexr runtime is set to oculus

**Comment by Sapper1430** [comment]
How do I do that?

**Comment by Sapper1430** [comment]
Oh I that was a mod file but it's a oculus setting thank u for the help

**Comment by Sapper1430** [comment]
Sorry to be annoying but I have been trying alot of things to get it to switch and it is stuck on steam vr

**Comment by Nullmatic** [comment]
![image](https://github.com/DaXcess/LCVR/assets/6313678/fe0dab8b-5d46-4002-9f08-d5413d74b53c)
I found this which may help you switch the runtime
Here is the link to the post as well: https://www.reddit.com/r/oculus/comments/jf11f8/help_changed_open_xr_setting_to_steamvr_want_to/g9hy1x0/

**Comment by Sapper1430** [comment]
Thank you for this but I'm having an error as follows "Cannot edit ActiveRuntime: Error writing the value's of new contents."
