### ISSUE TITLE
LCVR Update v1.0.1

### ISSUE THREAD

**Issue by DaXcess** [DaXcess/LCVR#77]
Tracking issues in here for the next update

- [x] #76

Target game version: **V49**

**Comment by XxsjrapsxX** [comment]
Issues with vr players seeing other vr players hand movements seem common. Not sure as of why yet. I could not see my fellow vr players hand movements but my nonvr friend could see my vr movements but not his. Its weird and i think it may have something to do with whoever is hosting just a hypothesis though
