### ISSUE TITLE
Add a color in compatibility list for mods that can't be used in VR, but wont cause issues for VR player outside of that.

### ISSUE THREAD

**Issue by jacobmix** [DaXcess/LCVR#78]
Add a color (orange or such) in compatibility list for mods that can't be used in VR, but wont cause issues for VR player outside of that.
Like WalkieUse for example. It let's non VR players us the keybind, but VR player still has to select the walkie. No real issue caused.

Might also be good to note if playing in a modpack if not supported mods can be disabled, but still let you play in the same modpack.
Like the "Reserved" mods. If VR players can just disable those, and play with desktop players using the mods fine.

Also explaining what is wrong if you use unsupported mods more clearly. Like MoreEmotes/BetterEmotes.
Hands get stuck way above the player making the experience basically unplayable. (Btw you can use TooManyEmotes instead)

**Comment by sweetlanzi** [comment]
You mentioned that you can use the Toomanyemotes module instead, but after I enable it, the game screen freezes, and after I turn it off, the game works fine.

**Comment by jacobmix** [comment]
Strange. Not home to test current versions. But it's shows it should work on the compatible mod list.
Just edit the config: `FlipMods.TooManyEmotes.cfg->Emote Radial Menu->DisableEmotingForSelf->True. `

**Comment by sweetlanzi** [comment]
This function will prohibit you from using the emoticon function of the module, which is a pity. I hope they can be compatible with each other in the future.
