### ISSUE TITLE
TheMostLethalCompany

### ISSUE THREAD

**Issue by FamBoy32** [DaXcess/LCVR#79]
There is a modpack called the TheMostLethalCompany. When I tried to open up VR with the modpack I got an error unity network config not found. I was wondering if there is any support or any thing I need to update to support the modpack. Thank you!

**Comment by DaXcess** [comment]
There is no guaranteed that all mods are compatible, and trying to inject the VR mod into a modpack is almost certainly going to break the game. Here is a [compatibility sheet](https://docs.google.com/spreadsheets/d/1mSulrvMkQFtjF_BWDeSfGz9rm3UWKMywmUP1yhcgCGo/edit#gid=0) which contains all currently known (in)compatible mods.
