### ISSUE TITLE
No Arms after death (Version 1.0.0)

### ISSUE THREAD

**Issue by ToastedOven** [DaXcess/LCVR#80]
Reproduction steps:

Using HTC Vive Gen 1 (unknown in this matters)

Launch game with just bepinex + LethalCompanyVR installed

Join or host a game

once in game, die

no arms on death screen, but they return after you respawn just fine.

I am assuming this is not intended behavior based on 
![Discord_dyPbYs4Sp4](https://github.com/DaXcess/LCVR/assets/49164897/01babb16-c6e8-4c6f-9284-677a397ae5eb)

**Comment by DaXcess** [comment]
Hey there, they were referring to **after** a player respawns. In spectator screen there are no arms and no player model as that seems overkill, especially for a 1.0 version. The spectator cam is implying that once the player dies there are no active XR rendering camera's, which means the screen for the VR player will show the last (few) frame(s) from before the last camera was disabled.
And with the arms they mean that once the player respawns there are no arms.

**Comment by ToastedOven** [comment]
I see, I thought "spectator cam/arms" meant to expect hands in the spectator camera. The actual issue was fixed by letting VR load before emotes, so as of LethalEmotesApi 1.1.15 the real issue no longer occurs
