### ISSUE TITLE
[Request] More fun features that seem cool to add!

### ISSUE THREAD

**Issue by TinyDerp** [DaXcess/LCVR#82]
I just had some cool funny ideas on what to add in the future when the mod becomes more stable.

1. The ability to duel wield items. For example in one hand you have a flashlight and in the other a walkie-talkie.
2. This is like and add on to the first features request. If there's a two handed object you need actually use both of your hands.
3. A replacement for the inventory feature. Something like you have to place items on your person instead of them just vanishing. This can also be used to display how much someone is carrying something.
4. This might be an easy one and also might be in the mod already. If you crouch IRL the in game player also crouches. This can be done with some type of height trigger or something (don't know how I'm not good at coding).
5. This seems like an unreal request to ask but I'm still gonna ask it. Can u make the terminal keyboard actually function pls 🥺.
6. Also the ability to move the lever and the pully rope thing on the loud horn actually moveable. Again this seems something that I should not me asking of you but still this is just a list of ideas and you don't have to make any of these a reality.

You've done a great job already and I don't expect you to add any of these features, but I'm still gonna put this out there so if anyone plans on making an add-on to the already existing amazingly made VR mod  the at least there's an idea list.

Thanks for listening me ramble and I hope you have an amazing day.

Edit 1:
Full body tracking would be nice

**Comment by DaXcess** [comment]
Going though old issues

point 1, 2 and 3 are not vanilla friendly, and this mod is client-side only
4 is implemented
5 requires custom models and I can't model
6 is implemented
