### ISSUE TITLE
Visual issues [Valve Index]

### ISSUE THREAD

**Issue by DrunkOnSuccess** [DaXcess/LCVR#84]
In certain locations or scenarios different effects get added to one lens display and not the other, such as on Experimentation. Infront of where the ship lands between the ladder and the ship a slight blur effect gets added to the right lens but not the left, this goes away once in the ship or up the ladder. Rooms with leaking steam pipes also does the same, it's likely that visual effects for whatever reason are amplified on the right lens. Corridors with turned on lights and steam also blinds the player, for some reason it becomes very very bright and genuinely hurts to look at.

**Comment by pembem22** [comment]
Same issue on Q2.

![20240116174810_1_vr](https://github.com/DaXcess/LCVR/assets/24252798/d22c11c3-53ae-4e6b-8d9d-ed445ab9fa05)
This screenshot, for example. After entering the ship and turning away from the entrance, volumetrics look wrong in the left eye. Exiting the ship fixes the problem.

**Comment by DrunkOnSuccess** [comment]
> Same issue on Q2.
> 
> ![20240116174810_1_vr](https://private-user-images.githubusercontent.com/24252798/297132809-d22c11c3-53ae-4e6b-8d9d-ed445ab9fa05.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0Mjc4NzgsIm5iZiI6MTcwNTQyNzU3OCwicGF0aCI6Ii8yNDI1Mjc5OC8yOTcxMzI4MDktZDIyYzExYzMtNTNhZS00ZTZiLThkOWQtZWQ0NDVhYjlmYTA1LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE2VDE3NTI1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEzODcwNTliOWRhYzQzYzJjYWI2NzQ2ZDJiODZhMWY0YTdiZDBjOTE5NWMxYWU4ZDM4M2FmYTdkMTU4NTU1ZDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.au1VMJNOFPdhi6LPDLALlA1dHnlaecREatvUQftrbsM) This screenshot, for example. After entering the ship and turning away from the entrance, volumetrics look wrong in the left eye. Exiting the ship fixes the problem.

Yep, that looks pretty much like what's up on my end too, one lens has an effect and the other does not. I can withstand a lot of things in VR, I don't get any form of motion or reality sickness but this issue does cause me genuine dizzyness and mild sickness.

**Comment by pembem22** [comment]
Still a problem in v1.1.0.

![20240121223024_1_vr](https://github.com/DaXcess/LCVR/assets/24252798/5e3eab5d-27af-44a9-8ddb-2599888c4848)
![20240121224056_1_vr](https://github.com/DaXcess/LCVR/assets/24252798/45515fc8-0dd9-41bf-9d98-47e359d3fc48)

**Comment by pembem22** [comment]
The issue is still present in v1.1.9:
![20240219234220_1_vr](https://github.com/DaXcess/LCVR/assets/24252798/d1530186-a7c9-44e5-8f83-751dd6324cc5)
