### ISSUE TITLE
BetterEmotes breaking arms and all animations

### ISSUE THREAD

**Issue by DrunkOnSuccess** [DaXcess/LCVR#85]
When using LCVR with BetterEmotes (and likely any other similar mods) will completely break all animations and the position of the VR players arms.

All non-vr players will glide around with zero animation.
VR players will not be able to see or control their arms (unless they look up, they can be seen floating above the head.)
All non-vr players will see the VR players arms without issue.
All non-vr players will not see any leg movement/animations for the VR player

**Comment by DizzyJune** [comment]
Maybe you should have checked the compatibility spreadsheet.
![image](https://github.com/DaXcess/LCVR/assets/74737360/43c986e8-a752-4e10-9870-36f28b740c2c)

**Comment by DaXcess** [comment]
Yeah most emote mods are incompatible
