### ISSUE TITLE
The Method for Custom Bindings is Terribly Inconvenient

### ISSUE THREAD

**Issue by Unsey-Games** [DaXcess/LCVR#86]
Is there a good reason that we have to push to a Github repository just to change our controller bindings? I don't have that much knowledge of modding so I wouldn't really know, but I feel like it would be better to just let players replace the binding json file manually instead of needing someone to check the repo to even _test_ your bindings, let alone actually use them.

Again, there could be a technical reason for this that I'm not aware of but it just seems like an unnecessary complication to me.

**Comment by DizzyJune** [comment]
You can change your controller bindings in-game.

**Comment by Unsey-Games** [comment]
> You can change your controller bindings in-game.

Is there something I missed? SteamVR's bindings menu has only button names and no action names, and the LC binding menu is disabled in VR.
