### ISSUE TITLE
[Oculus Rift S] Strange jittering and FOV adjustments

### ISSUE THREAD

**Issue by AurenTheGuy** [DaXcess/LCVR#87]
Tried capturing footage of it but unfortunately my video capture of the desktop view displays none of the issues experienced. While in the headset however, the game feels extremely jittery and the vertical field of view seemingly adjusts or changes when moving forwards and backwards in real space and not in the game. I've tried disabling all mods except for LCVR, reinstalling the game, and changing the OpenXR runtime on the off chance it had anything to do with it (running the game with Oculus set to the OpenXR runtime crashes Lethal Company immediately, but I'm assuming that's because it was never intended to run with it anyway), and unfortunately none of these have fixed the issue. I'm thankfully not plagued by motion sickness, but it's still an extremely jarring visual hamper and I do not know what it is caused by.

**Comment by AurenTheGuy** [comment]
I should add it's seemingly not a performance issue. OpenXR toolkit shows the game locked 80fps with no dips even with the prevalence of the visual glitches.

**Comment by Chiefsam34** [comment]
I had the same issue. Also when moving up and down it would go almost all the way to the top of the ship and down to the floor. It wouldn't properly match the actual movement. If DaXcess does try fixing this issue I'd be willing to help test to make sure the bug is gone if needed. (assuming there aren't already other people with a Oculus Rift S available to help test)

**Comment by Altived** [comment]
if you need help on this you could join the official discord bc it is hard to explain on here

**Comment by AurenTheGuy** [comment]
Not sure what fixed it, either the new update or the Oculus app update, but regardless it now launches with Oculus set to the active OpenXR runtime and no longer jitters, so I'm assuming this was the issue.
