### ISSUE TITLE
[Quest 3] Jittering on right eye only

### ISSUE THREAD

**Issue by Wayd-e** [DaXcess/LCVR#89]
Like the title suggests, I'm having an issue where the right eye of the headset is having weird stuttering/jittering issues. The left eye is perfectly fine and doesn't have any problems though, so not sure what could be causing it. For linking, I am using the Steam Link app on the headset to connect to my PC

Any help is appreciated!

**Comment by bavninja** [comment]
Don't use steam link app, set oculus or virtual desktop as default for openxr
