### ISSUE TITLE
Blue border on Reverb G2

### ISSUE THREAD

**Issue by matejdro** [DaXcess/LCVR#96]
On Reverb G2 headset (with Steam VR) there is a blue border around the game:

![vlcsnap-2024-01-14-11h15m23s847](https://github.com/DaXcess/LCVR/assets/507922/dedb19d7-8152-4d73-97fd-43547c0be8a8)

This border is not perfectly outside Headset's view (some of the border is visible on the fringes of the headset), resulting in weird blue glow in dark scenes (for example, in the menu).

**Comment by alzahhar3** [comment]
same on quest 3
