### ISSUE TITLE
VR conflicts with Too Many Emotes mod

### ISSUE THREAD

**Issue by sweetlanzi** [DaXcess/LCVR#98]
About 3 seconds after I entered the spaceship, the screen would freeze. The following is the error log when the console is running (it keeps highlighting this code in red font): User
[Info : Unity Log] [HELMET_CAMERAS] ERROR NULL REFERENCE
[Error : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
LCVR.Player.IKRigFollowVRRig.LateUpdate () (at <9733afb8846f4320bf8b90e382316eb1>:0)

[Info : Unity Log] [HELMET_CAMERAS] ERROR NULL REFERENCE
[Error : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
LCVR.Player.IKRigFollowVRRig.LateUpdate () (at <9733afb8846f4320bf8b90e382316eb1>:0)

**Comment by Sapper1430** [comment]
The problem is the mod doesn't support it so ur gonna have to remove it there is a list of what mods can be used but not all mods are on there(just scroll down to the description and it's in there)

**Comment by LegionMG** [comment]
Turn off emoting for self in config of Too Many Emotes

**Comment by Sapper1430** [comment]
Try too many emotes

**Comment by DaXcess** [comment]
TooManyEmotes already has configuration (disable emoting for self) that makes it work with the VR mod
